Electric-Coin-Company/zashi-android

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/ux-report.md
- .github/pull_request_template.md
- .gitignore
- README.md
- docs/Architecture.md
- docs/CODE_REVIEW_GUIDELINES.md
- docs/CONDUCT.md
- docs/CONTRIBUTING.md
- docs/README.md
- docs/Setup.md
- docs/responsible_disclosure.md
- docs/testing/local_coverage.md
- docs/testing/manual_testing/README.md
This is similar to the recent iOS documentation changes.
I have not yet included lint or static analysis configuration yet, as that will require Gradle modules to be set up.  I'll do that in a separate PR.
To help speed up review, these are the significant differences from the iOS documentation:
* I tried to make the readme very accessible.  Let me know if you feel like it has been over simplified.
* The security reporting guidelines varied between README, CONTRIBUTING, and the issue template.  I deferred to the version in the README, which points to a markdown file in another Zcash repo.
* The CONTRIBUTING file had some overlap with the CODE_REVIEW_GUIDELINES.md and CONDUCT.md.  I removed some of the extra verbiage, as I feel like most of it should be covered by the …
> [#2] Add project documentation and templates

- .github/ISSUE_TEMPLATE/bug-report.md
- app/src/androidTest/java/cash/z/ecc/app/ScreenshotTest.kt
- sdk-ext-lib/build.gradle.kts
- sdk-ext-lib/src/androidTest/java/cash/z/ecc/sdk/model/ZatoshiTest.kt
- sdk-ext-lib/src/androidTest/java/cash/z/ecc/sdk/model/ZecStringTest.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/fixture/ZecRequestFixture.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/model/Zatoshi.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/model/ZecRequest.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/model/ZecString.kt
- settings.gradle.kts
- ui-lib/build.gradle.kts
- ui-lib/src/androidTest/java/cash/z/ecc/ui/screen/request/view/RequestViewTest.kt
- ui-lib/src/androidTest/java/cash/z/ecc/ui/screen/seed/view/SeedViewTest.kt
- ui-lib/src/androidTest/java/cash/z/ecc/ui/screen/settings/view/SettingsViewTest.kt
- ui-lib/src/main/java/cash/z/ecc/ui/MainActivity.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/common/Button.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/home/view/HomeView.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/request/view/RequestView.kt
- ui-lib/src/main/res/ui/request/values/strings.xml
This provides an initial scaffold for ZEC requests. There are a lot of followup issues to address, as a variety of changes are needed in the SDK to fully support ZEC request as well as changes in the Secant app too.  These should cover most of the followup issues needed:
https://github.com/zcash/zcash-android-wallet-sdk/issues/397
https://github.com/zcash/zcash-android-wallet-sdk/issues/412 
https://github.com/zcash/secant-android-wallet/issues/202
https://github.com/zcash/secant-android-wallet/issues/218 
https://github.com/zcash/secant-android-wallet/issues/215 
https://github.com/zcash/secant-android-wallet/issues/219 
https://github.com/zcash/secant-android-wallet/issues/217
This code review checklist is intended to serve as a starting point for the author and reviewer, although it …
> [#135] Request ZEC scaffold

- .github/workflows/pull-request.yml
- app/build.gradle.kts
- app/src/androidTest/java/co/electriccoin/zcash/app/ScreenshotTest.kt
- build.gradle.kts
- preference-impl-android-lib/build.gradle.kts
- spackle-lib/src/main/java/co/electriccoin/zcash/spackle/FirebaseTestLabUtil.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/MainActivity.kt
This wasn't a high priority issue, but it was a 1-line code change that me debug whether Firebase Test Lab is now working correctly.  The changes I made were:
- Ensure that test results are collected by GitHub Actions if the prior build steps fail
- Use higher resolution test devices, to bypass issues with our UI on small screens
- Disable screenshot tests on pre-Q devices
- Disable screenshot tests on Firebase Test Lab
- Enable test orchestrator for all Firebase Test Lab tests, because there's not a way to enable orchestrator on a per-module basis
As next steps, there are several new followup issues to improve the Firebase Test Lab integration
- #282
- #285
- #286
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be …
> [#278] Store wallet birthday as null

- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/profile/view/ProfileView.kt
This pull request contains these 2 changes:
- Remove `tint` attribute from _Icon_ definition of _TopAppBar_ of the **Profile** screen. As the **Send** and **Request** screens also do not have this `tint` attribute in theirs _TopAppBar_ components included, there is probably no need to have it here on **Profile** screen. Moreover, we are now more consistent. Tested in both Light and Dark themes. Tested on Android API SDK 24, 27, 29 and 32 devices. Works as expected.
- Minor code style refactoring.
Closes https://github.com/zcash/secant-android-wallet/issues/244.
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth …
> [#244] Back button is invisible on Profile screen.

- ui-lib/src/main/java/co/electriccoin/zcash/ui/MainActivity.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreView.kt
- Tested these 3 ways how to check monkey test runner: `ActivityManager.isUserAMonkey()`, `ActivityManager.isRunningInUserTestHarness()`, `Settings.System "firebase.test.lab"`. Tested by releasing another app build to Firebase TestLab and Google Internal Test (Pre-launch reports).
- Implemented the check via Settings.System way, as it appeared to be working well on both cloud tests.
- Added `MainActivity.changeAppFlowForAutomationTests()` function to change the app flow while messed with by a monkey test runner. It simply persist existing wallet with mock seed and related flag to persistence in case of both user action (Create a new wallet or Import existing wallet) and let current implementation to be notified about it and goes to home screen.
- Filed and marked a new issue related to …
> [#179] Improve Ability to Run Application under Robo Test

- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreView.kt
In some cases we need to hide the software keyboard manually, as it stays shown after all words are filled successfully.
- Implemented with `LocalSoftwareKeyboardController`.
- The alternative way of implementation with `LocalFocusManager` didn't work so well here.
Closes https://github.com/zcash/secant-android-wallet/issues/409.
> [#409] Keep showing keyboard over Home screen

- .github/workflows/pull-request.yml
- .idea/runConfigurations/assemble.xml
- .idea/runConfigurations/assembleAndroidTest.xml
- .idea/runConfigurations/ktlintFormat.xml
- app/build.gradle.kts
- build.gradle.kts
- docs/Setup.md
- gradle.properties
- spackle-lib/src/main/java/co/electriccoin/zcash/spackle/EmulatorWtfUtil.kt
This pulls screenshots off the cloud testing provider from our screenshots test.  You can confirm they exist when the CI job completes—they will be inside the test results for app module.
There are some followup items after this is done.  Specifically:
- Some of the screenshots are weird or blank.  This indicates a pre-existing timing issue #440
- We likely want a matrix for screenshots to cover light and dark mode, as well as different locations #439
There are a few other enhancements inside this:
- Can now run Firebase Test Lab with user authentication, in addition to a long-lived service API key
- Some of our run configurations were tweaked.  ktlint is now ktlintFormat.
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not …
> [#190] Pull screenshots on CI

- ui-lib/src/main/java/co/electriccoin/zcash/ui/MainActivity.kt
Solves multiple calls to Play Core with LaunchedEffect.
Closes https://github.com/zcash/secant-android-wallet/issues/450.
> [#450] Multiple calls to Play Core

- docs/testing/Testing.md
- I can confirm that these all are working locally for me (all run with `PIS_ANDROID_INSTRUMENTATION_TEST_COVERAGE_ENABLED=true`):
- `./gradlew ui-lib:connectedCheck`
- `./gradlew configuration-impl-android-lib:connectedCheck`
- `./gradlew crash-android-lib:connectedCheck`
- `./gradlew preference-impl-android-lib:connectedCheck`
- `./gradlew sdk-ext-lib:connectedCheck`
- `./gradlew spackle-android-lib:connectedCheck`
- `./gradlew ui-design-lib:connectedCheck`
- All create `index.html` with test coverage overview
- These two below work too, but do not create the coverage overview, which we can consider as a correct state, as they are of `com.android.test` plugin type, and thus they have their tests located in the main package.
- `./gradlew …
> [#705] Instrumentation coverage generation fails locally

- CHANGELOG.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/TextField.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/internal/Typography.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/model/RestoreStage.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreView.kt
- ui-lib/src/main/res/ui/restore/values/strings.xml
- ui-screenshot-test/src/main/java/co/electroniccoin/zcash/ui/screenshot/ScreenshotTest.kt
- Reworked Restore Seed-Birthday height screen
- Contains UI, screen logic and tests
- Closes #1064
https://github.com/Electric-Coin-Company/zashi-android/assets/9017390/28508c36-3f09-4023-a8bb-66e24f275e0a
> **Note**
> **Note**
[^1]: _Code often looks different when …
> [#1064] Restore Seed-Birthday Screen

- ui-screenshot-test/src/main/java/co/electroniccoin/zcash/ui/screenshot/ScreenshotTest.kt
- Closes #817
- This issue is obsolete, as we introduced a new check on available balance to enable the Send button on the Send Form screen. The test can’t easily bypass this new check.
> **Note**
> **Note**
[^1]: _Code often looks different when reviewing the diff in a browser, making it …
> [#817] Simplify Send screenshot test

- CHANGELOG.md
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/SendViewTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/view/SendViewAndroidTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/view/SendViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/AndroidSend.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/model/SendStage.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
- ui-lib/src/main/res/ui/send/values/strings.xml
- Closes #1201
- The changes also contain custom saver for SendStage
- The error is printed on the SendFailure screen as a simple text for now
- Changelog updated
> **Note**
> **Note**
[^1]: _Code often looks different when reviewing the diff in a browser, making it easier to spot …
> [#1201] Enhance SendStage.SendFailure with error

- CHANGELOG.md
- app/proguard-project.txt
- ui-lib/src/main/java/co/electriccoin/zcash/work/SyncWorker.kt
- ui-lib/src/main/java/co/electriccoin/zcash/work/WorkIds.kt
- A periodic background block synchronization has been added. When the device is connected to the internet using an unmetered connection and is plugged into the power, the background task will start to synchronize blocks randomly between 3 and 4 a.m.
- The background worker was in place but not fully working, plus was set to trigger randomly in 24 hours
- Closes #1151
- Closes #634
- Its follow-up #1249
> **Note**
> …
> [#1151] Background syncing

- app/build.gradle.kts
- build.gradle.kts
- gradle.properties
- Although this build flag is not transitive, and thus it does not cover SDK, it’s still a good approach to have it turned on
- Using the middle path with symbol_table value - this could be changed once needed
- Closes #1190 
> **Note**
> **Note**
[^1]: _Code often looks different when …
> [#1190] Add native debug symbols to app build

- CHANGELOG.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/AndroidBalances.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/sendconfirmation/AndroidSendConfirmation.kt
- ui-lib/src/main/res/ui/balances/values/strings.xml
- Closes #1434
These changes bring:
- Show successful shielding attempt Toast
- Actively trigger the balance refresh after the shielding (or sending) action is finished to shorten the time needed to refresh the transparent balance (and all balances too)
> **Note**
> **Note**
> It is good practice to provide before and after UI  **screenshots** in the description of this PR. This is only applicable for changes that modify …
> [#1434] Improve Shielding UX

- CHANGELOG.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Dialog.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/Dimens.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/account/AccountTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/account/history/HistoryTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/balances/BalancesTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/balances/model/WalletDisplayValuesTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/update/util/PlayStoreUtilTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/compose/BalanceWidget.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/compose/SynchronizationStatus.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/AuthenticationViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/AndroidAccount.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/view/AccountView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/view/HistoryView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/AndroidBalances.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/model/WalletDisplayValues.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/view/BalancesView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/AndroidHome.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/update/AndroidUpdate.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/update/view/UpdateView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/util/PlayStoreUtil.kt
- ui-lib/src/main/res/ui/balances/values/strings.xml
- ui-lib/src/main/res/ui/common/values/strings.xml
- ui-lib/src/main/res/ui/update/values/strings.xml
- Closes #1449
- Synchronizer status details are now available to users by pressing the simple status view. The details are displayed within the predefined Zashi dialog on the Balances and Account screens
- As this view also presents information about Zashi app updates available on Google Play, by pressing the view, the app redirects users to Google Play Zashi’s page
- As agreed, we’re moving towards more rounded corners in dialogs, which is part of these changes, too
- Added also several minor Balances screen UI improvements
- Improved biometric flow without any authentication method set on older Android versions
The error message in the dialog below is just a showcase:
> **Note**
>This code review checklist is intended to serve as a starting point for the author and …
> [#1449] Display Synchronizer details in dialog

- CHANGELOG.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/Navigation.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/AuthenticationViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/authentication/AndroidAuthentication.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/sendconfirmation/AndroidSendConfirmation.kt
- Closes #1496
- The onFailed callback now does not reset the helper compose variable anymore
- Toast duration shortened in the auth failed state to improve its UX
> **Note**
> **Note**
[^1]: _Code often looks different when reviewing the diff in a browser, making it …
> [#1496] Authentication success after previous failure

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- ui-lib/src/main/AndroidManifest.xml
- ui-lib/src/main/java/co/electriccoin/zcash/ui/MainActivity.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreView.kt
Closes #1467
This approach works for all screens universally - it resizes the window according to the soft keyboard and imePadding makes sure compose handles and animates this change correctly.
Without this approach we show the keyboard simply above the activity and hope there is enough space on the screen of the user to show the rest of the view.
On the second screenshot you can see that it really pushes everything up including the tabs. Such elements can be handled separately - we can hide them if necessary. However I left it this way becuase I don't feel like it's an issue.
| Feedback  | Receive funds |
| ------------- | ------------- |
| ![Screenshot_20240708_131842](https://github.com/Electric-Coin-Company/zashi-android/assets/173177868/96002517-39ff-4dbf-8365-a7a848cfd41c) | …
> [#1467] Activity resizing according to soft keyboard

- ui-lib/src/main/java/co/electriccoin/zcash/ui/MainActivity.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/extension/ComponentActivityExt.kt
Composition strategy handling for MainActivity.
> **Note**
[^3]: _While we are not looking for perfect coverage, the tool can point out potential cases that have been missed. Code coverage can be generated with: `./gradlew check` for Kotlin modules and `./gradlew connectedCheck …
> Activity Compose Composition Strategy handling

- crash-android-lib/src/androidTest/kotlin/co/electriccoin/zcash/crash/android/internal/local/Components.kt
- spackle-android-lib/src/androidTest/java/co/electriccoin/zcash/spackle/process/VersionCodeCompatTest.kt
- spackle-android-lib/src/main/kotlin/co/electriccoin/zcash/spackle/AndroidApiVersion.kt
- spackle-android-lib/src/main/kotlin/co/electriccoin/zcash/spackle/ClipboardManagerUtil.kt
- spackle-android-lib/src/main/kotlin/co/electriccoin/zcash/spackle/PackageManagerCompat.kt
- spackle-android-lib/src/main/kotlin/co/electriccoin/zcash/spackle/StrictModeCompat.kt
- spackle-android-lib/src/main/kotlin/co/electriccoin/zcash/spackle/process/AbstractProcessNameContentProvider.kt
- spackle-android-lib/src/main/kotlin/co/electriccoin/zcash/spackle/process/ProcessNameCompat.kt
> Android 15 strict mode update for unsafe intents

- tools/detekt.yml
> Detekt disabled complexity checks

- CHANGELOG.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/ZashiQr.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/Navigation.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/exchangerate/widget/StyledExchangeBalance.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/qrcode/model/QrCodeState.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/qrcode/view/QrCodeView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/qrcode/viewmodel/QrCodeViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/request/model/RequestState.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/request/view/RequestQrCodeView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/request/viewmodel/RequestViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/signkeystonetransaction/state/SignKeystoneTransactionState.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/signkeystonetransaction/view/SignKeystoneTransactionView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/signkeystonetransaction/viewmodel/SignKeystoneTransactionViewModel.kt
- The QR code image logic of the `QrCode` and `Request` screens has been refactored to work upon the newer `ZashiQr` component
- This is a prerequisite for Allow QR codes colors switching #1731
- Changelog updated
> **Note**
> **Note**
[^1]: _Code often looks different when reviewing the …
> QR code image logic refactoring

- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/listitem/ZashiListItem.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/usecase/CreateKeystoneAccountUseCase.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/integrations/view/IntegrationsView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/integrations/viewmodel/IntegrationsViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/settings/view/SettingsView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/settings/viewmodel/SettingsViewModel.kt
- ui-lib/src/main/res/ui/integrations/drawable-night/ic_integrations_keystone.xml
- ui-lib/src/main/res/ui/integrations/drawable/ic_integrations_keystone.xml
- ui-lib/src/main/res/ui/integrations/values-es/strings.xml
- ui-lib/src/main/res/ui/integrations/values/strings.xml
> Keystone added to integrations
