- .idea/runConfigurations/app_connectedCheck.xml
- app/src/androidTest/java/cash/z/ecc/app/TargetApiTest.kt
This change won't come into play until next year, most likely.  But it'll help ensure that we don't break the app when working on support for future versions of Android.
> [#74] Prevent accidental targeting of newer API levels

- ui-lib/src/main/java/cash/z/ecc/ui/screen/common/Chip.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/debug/view/DesignGuide.kt
- ui-lib/src/main/java/cash/z/ecc/ui/theme/Color.kt
- ui-lib/src/main/java/cash/z/ecc/ui/theme/Theme.kt
- ui-lib/src/main/java/cash/z/ecc/ui/theme/Typography.kt
> [#72] Add Chip Composable

- buildSrc/build.gradle.kts
> [#81] Fix Gradle warning during builds

- build-conventions/src/main/kotlin/zcash.kotlin-multiplatform-build-conventions.gradle.kts
- gradle.properties
> [#78] Fix build on Apple Silicon

- gradle.properties
This is a minor change—it doesn't really impact our app code because the codebase is still small and we aren't using R classes transitively yet.  Setting this flag will prevent transitive references going forward.
> [#87] Enable non-transitive R classes

- app/build.gradle.kts
- docs/Deployment.md
- gradle.properties
- settings.gradle.kts
This enables deployment to Google Play internal testing, implementing #42.
Note these changes cannot be fully tested until the signing and API keys are in place.  Non-deployed builds are continuing to work as expected (e.g. `./gradlew assemble`)
> [#42] Add app deployment process

- ui-lib/src/androidTest/java/cash/z/ecc/ui/screen/backup/view/BackupViewTest.kt
- ui-lib/src/main/java/cash/z/ecc/ui/MainActivity.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/backup/view/BackupView.kt
- ui-lib/src/main/res/ui/backup/values/strings.xml
Although the original issue #49 discussed creating reusable logic, the requirements of reusable logic are not yet clear.
Android does have some interesting functionality, where we could copy rich data to the clipboard.  This rich data could even include the wallet birthday to simplify pasting back into the app. However, such pasted the data would not be as nicely human readable.  The rich format is similar to an encoded URI string.
So until we determine what makes the most sense, I've kept this intentionally simple with just a plaintext string being copied.  This probably is going to most likely meet user expectations.
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a …
> [#49] Implement copy to clipboard

- ui-lib/src/main/java/cash/z/ecc/ui/MainActivity.kt
- ui-lib/src/main/java/cash/z/ecc/ui/util/AndroidApiVersion.kt
Older Android versions require a backwards compatibility library for loading custom fonts, and it turns out this can be slow.  This implements a solution to move that font loading to a background thread during app startup.  This helps reduce risk of triggering an Application Not Responding on older Android devices.
> [#101] Improve app startup pre API 26

- ui-lib/src/androidTest/java/cash/z/ecc/ui/screen/backup/view/BackupViewTest.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/backup/view/BackupView.kt
> [#118] Fix backup verification UI

- ui-lib/src/main/java/cash/z/ecc/ui/MainActivity.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/backup/view/BackupView.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/common/GradientSurface.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/debug/view/DesignGuide.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/home/view/HomeView.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/onboarding/view/OnboardingView.kt
- ui-lib/src/main/java/cash/z/ecc/ui/theme/Theme.kt
This adds the background gradient to from the design, instead of a static background color, by hoisting the background to the MainActivity instead of having each screen having to manage the background.
This also fixes the height of the onboarding screens.
> [#65] Add background gradient

- gradle/wrapper/gradle-wrapper.properties
> [#128] Gradle 7.3.2

- gradle/wrapper/gradle-wrapper.properties
> [#154] Gradle 7.3.3

- gradle.properties
- sdk-ext-lib/build.gradle.kts
- sdk-ext-lib/src/androidTest/java/cash/z/ecc/sdk/model/WalletAddressesTest.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/fixture/WalletAddressesFixture.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/model/WalletAddresses.kt
- ui-lib/build.gradle.kts
- ui-lib/src/androidTest/java/cash/z/ecc/ui/screen/wallet_address/view/WalletAddressViewTest.kt
- ui-lib/src/main/java/cash/z/ecc/ui/MainActivity.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/common/Text.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/home/viewmodel/WalletViewModel.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/restore/view/RestoreView.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/wallet_address/view/WalletAddressView.kt
- ui-lib/src/main/java/cash/z/ecc/ui/theme/Color.kt
- ui-lib/src/main/java/cash/z/ecc/ui/theme/Theme.kt
- ui-lib/src/main/java/cash/z/ecc/ui/theme/Typography.kt
- ui-lib/src/main/res/ui/wallet_address/values/strings.xml
Implements a details screen showing various wallet addresses
Some known issues requiring followup in future pull requests:
- #159 Colors for light theme have not been defined yet
- #160 Color blocks have 2x borders along the top/bottom of the middle item
- #161 Some address types display placeholder values
> [#62] Wallet details scaffold

- docs/testing/manual_testing/QR Code Generation.md
- gradle.properties
- sdk-ext-lib/src/androidTest/java/cash/z/ecc/sdk/model/WalletAddressesTest.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/fixture/WalletAddressFixture.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/fixture/WalletAddressesFixture.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/model/WalletAddress.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/model/WalletAddresses.kt
- settings.gradle.kts
- ui-lib/build.gradle.kts
- ui-lib/src/androidTest/java/cash/z/ecc/ui/MainActivityCompanionTest.kt
- ui-lib/src/androidTest/java/cash/z/ecc/ui/screen/profile/view/ProfileViewTest.kt
- ui-lib/src/androidTest/java/cash/z/ecc/ui/screen/wallet_address/view/WalletAddressViewTest.kt
- ui-lib/src/main/java/cash/z/ecc/ui/MainActivity.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/common/Button.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/profile/util/AndroidQrCodeImageGenerator.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/profile/util/JvmQrCodeGenerator.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/profile/util/QrCodeGenerator.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/profile/util/QrCodeImageGenerator.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/profile/view/ProfileView.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/wallet_address/view/WalletAddressView.kt
- ui-lib/src/main/java/cash/z/ecc/ui/theme/Color.kt
- ui-lib/src/main/java/cash/z/ecc/ui/theme/Theme.kt
- ui-lib/src/main/res/ui/profile/values/strings.xml
- ui-lib/src/main/res/ui/wallet_address/values/strings.xml
> [#145] Profile scaffold

- ui-lib/build.gradle.kts
- ui-lib/src/androidTest/java/cash/z/ecc/ui/screen/seed/view/SeedViewTest.kt
- ui-lib/src/androidTest/java/cash/z/ecc/ui/screen/settings/view/SettingsViewTest.kt
- ui-lib/src/main/java/cash/z/ecc/ui/MainActivity.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/common/Button.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/home/viewmodel/WalletViewModel.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/onboarding/state/OnboardingState.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/restore/view/RestoreView.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/seed/view/SeedView.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/settings/view/SettingsView.kt
- ui-lib/src/main/java/cash/z/ecc/ui/theme/Color.kt
- ui-lib/src/main/java/cash/z/ecc/ui/theme/Theme.kt
- ui-lib/src/main/res/ui/seed/values/strings.xml
- ui-lib/src/main/res/ui/settings/values/strings.xml
Settings which are not yet implemented have not been included to not introduce non-functional buttons into the UI.
Followup issue #38 covers one of the key settings, which is how we'll implement authorization in the app
> [#143] Add settings scaffold

- .github/workflows/pull-request.yml
> [#186] Fix running Kotlin module tests on CI

- gradle.properties
> [#178] Re-enable Gradle build cache

- app/build.gradle.kts
- app/src/androidTest/AndroidManifest.xml
- app/src/main/AndroidManifest.xml
- app/src/main/java/cash/z/ecc/app/AppImpl.kt
In a separate pull request, the class packages will be refactored to match this new package name.  This is under issue #231 .
> [#177] Change application package name

- docs/Architecture.md
Note to reviewer: look at the rendered markdown here
https://github.com/zcash/secant-android-wallet/blob/224-add-dependency-diagram/docs/Architecture.md#modules
Also fixed a typo in the documentation, as `build-conventions` was renamed to `build-convention` a few weeks ago to accomodate included builds
> [#224] Add module dependency diagram

- app/build.gradle.kts
Although the signing configuration was created previously, there was an important missing step which was configuring the release build type to use the signing configuration.  This resolves that issue.
> [#256] Fix release signing config

- .github/actions/setup/action.yml
- .github/workflows/deploy.yml
- .github/workflows/pull-request.yml
- docs/Build integrity.md
This does two big things:
- Improves build security by using SHAs instead of tags to pin the GitHub Actions that we use
- Kills duplicate build jobs (e.g. someone pushes a change while a PR is still building the prior push)
> Improve builds on GitHub Actions

- ui-lib/src/androidTest/java/cash/z/ecc/ui/screen/profile/view/ProfileViewTest.kt
- ui-lib/src/main/java/cash/z/ecc/ui/screen/profile/view/ProfileView.kt
> [#247] Hide inert address-book button

- .github/workflows/deploy.yml
This fixes an issue with our Google Play deployment.
> [#267] Fix Google Play service key variable name

- app/build.gradle.kts
This is a fix for our CI deployment, where we don't want the testnet variant of the app to be published to Google Play.
> [#271] Disable publishing of testnet

- .github/workflows/deploy.yml
With this change, our deployments will now be made to an internal testing track.  (Previously, we created a draft but didn't commit it which allowed us to safely verify that the deployment and API keys were set up correctly.)
> [#273] Enable deployment to Google Play

- sdk-ext-lib/src/androidTest/java/cash/z/ecc/sdk/model/ZecRequestTest.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/fixture/Zip321UriBuildFixture.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/fixture/Zip321UriParseFixture.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/model/ZecRequest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/MainActivity.kt
Includes `Zip321UriBuildFixture` for the `toUri()` method from the Rust layer.
Includes `Zip321UriParseFixture` for the `fromUri()` method from the Rust layer.
Closes https://github.com/zcash/secant-android-wallet/issues/283.
> [#283] Kotlin API for Zcash URI parser

- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/backup/view/DropDown.kt
Solution to this issue was in setting colors to those missing text and triangle icon views:
- Changed color of the ChipDropDown text.
- Changed tint color of the ChipDropDown text disclosure triangle.
Colors were set to be the same as for the Chip component.
Closes https://github.com/zcash/secant-android-wallet/issues/245.
> [#245] Onboarding test doesn't show selections.

- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/backup/view/BackupViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/profile/view/ProfileViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/backup/view/BackupView.kt
- Scrolling enabled for screens from Backup and Profile parts of the app.
- UI tests improved to always scroll to the desired views before working with them.
- Tested on devices with very small screens:
- _3.4in WQVGA API 24 (LDPI)_
- _5.4in FWVGA API 24 (MDPI)_
- All our UI tests work now on these devices with low resolution.
Closes https://github.com/zcash/secant-android-wallet/issues/282.
> [#282] Tests fail on low resolution devices.

- .github/workflows/deploy.yml
- .github/workflows/pull-request.yml
- app/build.gradle.kts
This PR adds two things:
- Runs our sanity tests against a universal APK
- Generates universal APK as part of deployment
There are possible slight differences between an APK from assembleRelease versus one generated by converting an app bundle.  This helps bring our build outputs and tests closer to what users would receive (although we aren't generating device-specific APKs).
> Generate universal APK from app bundle

- spackle-lib/src/main/java/co/electriccoin/zcash/spackle/model/Index.kt
- ui-lib/src/androidTest/AndroidManifest.xml
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/backup/TestBackupActivity.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/backup/model/TestChoicesTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/backup/view/BackupIntegrationTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/backup/view/BackupTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/backup/view/BackupViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/MainActivity.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/fixture/TestChoicesFixture.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/backup/AndroidBackup.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/backup/ext/TestChoicesExt.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/backup/state/TestChoices.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/backup/view/BackupView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/backup/viewmodel/BackupViewModel.kt
This PR fixes crashing the app while in backup flow. Tested with different ways of configuration changes (e.g. kill the app in background, change theme/orientation, etc.). But there is one thing, which needs to be discussed first - do we want to introduce Parcelable to our code? As I know its not directly supported by Kotlin Multiplatform. But it can be done like described for example here in this [post](https://www.droidcon.com/2021/11/29/android-parcelable-in-kotlin-multiplatform/).
Closes https://github.com/zcash/secant-android-wallet/issues/356, https://github.com/zcash/secant-android-wallet/issues/246.
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling …
> [#356] Crash verify backup while save state

- app/src/androidTest/java/co/electriccoin/zcash/app/ScreenshotTest.kt
- docs/Build integrity.md
- ui-lib/build.gradle.kts
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/about/AboutViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/profile/view/ProfileViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/MainActivity.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/fixture/VersionInfoFixture.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/about/AndroidAboutView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/about/model/VersionInfo.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/about/view/AboutView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/profile/AndroidProfile.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/profile/util/ProfileConfiguration.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/profile/view/ProfileView.kt
- ui-lib/src/main/res/ui/about/values/strings.xml
- ui-lib/src/main/res/ui/profile/values/strings.xml
This provides a basic scaffold for the About screen.  There are several followup issues:
- #392 update the in-app legal text
- #398 Add open source attributions
> [#296] About screen scaffold

- app/build.gradle.kts
- app/src/androidTest/java/co/electriccoin/zcash/app/ScreenshotTest.kt
- settings.gradle.kts
- test-lib/build.gradle.kts
- test-lib/src/main/AndroidManifest.xml
- test-lib/src/main/kotlin/co/electriccoin/zcash/test/UiTestPrerequisites.kt
- test-lib/src/main/kotlin/co/electriccoin/zcash/test/ZcashUiTestRunner.kt
- ui-lib/build.gradle.kts
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/backup/view/BackupIntegrationTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/backup/view/BackupViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/onboarding/view/OnboardingIntegrationTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/onboarding/view/OnboardingViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/request/view/RequestViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/seed/view/SeedViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/view/SendViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/settings/view/SettingsViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/support/view/SupportViewIntegrationTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/support/view/SupportViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/wallet_address/view/WalletAddressViewTest.kt
This improves the reliability of UI tests, especially on physical devices, by helping ensure the screen is on.
To verify this is working, try running the UI and app tests on a physical device which has the screen turned off at the start.  You can also try turning off the screen while the tests are running.  In each case, the assertion error message will be much more clear about why the test failed and the tests will fail much more quickly.
> [#290] Screen on for UI tests

- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/wallet_address/view/WalletAddressView.kt
- Solved by removing unnecessary tint parameter.
- This issue is the same as already solved once for the Profile screen https://github.com/zcash/secant-android-wallet/pull/357.
- Closes https://github.com/zcash/secant-android-wallet/issues/424.
> [#424] Back button invisible on Wallet addresses screen.

- app/build.gradle.kts
- build-convention/src/main/kotlin/zcash.android-build-conventions.gradle.kts
- preference-impl-android-lib/build.gradle.kts
- sdk-ext-lib/build.gradle.kts
- sdk-ext-ui-lib/build.gradle.kts
- spackle-lib/build.gradle.kts
- test-lib/build.gradle.kts
- ui-design-lib/build.gradle.kts
- ui-lib/build.gradle.kts
> [#6] Refactor kotlinOptions to build-conventions

- docs/Setup.md
- gradle.properties
- settings.gradle.kts
> [#441] Make included build path configurable

- app/build.gradle.kts
- app/src/androidTest/java/co/electriccoin/zcash/app/ScreenshotTest.kt
- app/src/androidTest/java/co/electriccoin/zcash/app/test/GetStringResource.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Override.kt
- ui-lib/build.gradle.kts
- ui-lib/src/main/java/co/electriccoin/zcash/ui/MainActivity.kt
- ui-lib/src/main/res/ui/common/values/themes.xml
> [#439] Take light/dark screenshots

- docs/Setup.md
> Update setup documentation

- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/onboarding/TestOnboardingActivity.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/onboarding/view/OnboardingTestSetup.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/MainActivity.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/AndroidOnboarding.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/view/OnboardingView.kt
> [#465] Add onboarding debug menu

- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/settings/view/SettingsViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/global/WalletCoordinator.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/MainActivity.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/backup/state/BackupState.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/AndroidHome.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/view/HomeView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/viewmodel/WalletViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/settings/AndroidSettings.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/settings/view/SettingsView.kt
> [#483] Fix crash when wiping wallet

- ui-lib/src/main/java/co/electriccoin/zcash/ui/MainActivity.kt
- Solve also debouncing issue on screens navigation
- Implemented with extension function on NavHostController, which compares actual and final destinations
Closes https://github.com/zcash/secant-android-wallet/issues/416, https://github.com/zcash/secant-android-wallet/issues/214.
> [#416] Robo test blank screens

- build-conventions-secant/src/main/kotlin/secant.rosetta-conventions.gradle.kts
- build.gradle.kts
> [#493] Warn when running under Rosetta

- .github/workflows/deploy.yml
- .github/workflows/pull-request.yml
- docs/Setup.md
> [#498] Generate debug builds on CI

- .github/dependabot.yml
> [#497] Configure Dependabot for GitHub Actions

- ui-integration-test-lib/build.gradle.kts
- ui-integration-test-lib/src/androidTest/java/co/electriccoin/zcash/ui/integration/test/screen/update/viewmodel/AppUpdateCheckerMock.kt
- ui-integration-test-lib/src/androidTest/java/co/electriccoin/zcash/ui/integration/test/screen/update/viewmodel/UpdateViewModelTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/update/util/PlayStoreUtilTest.kt
Logic of this test is built upon `AppUpdateCheckerMock` component, which uses `FakeAppUpdateManager` from GP core lib, and thus it should not be influenced by connection of GP Services. The test seemed to be set up right. So I moved this test to `ui-integration-test-lib`, which has the orchestrator turned on and may influence the correct initial state of related components, as it was failing on the first condition of the first callback event.
Closes https://github.com/zcash/secant-android-wallet/issues/485.
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code …
> [#485] Test Failure For UpdateViewModel

- .github/actions/antivirus/Dockerfile
- .github/actions/antivirus/action.yml
- .github/actions/setup/action.yml
- .github/workflows/deploy.yml
This runs a malware scan on our release binaries. The main purpose is as early warning system to catch instances where antivirus software might have a false positive.
Due to how the Gradle Play Publisher plugin works, it is more difficult to create a build, scan it, then upload it.  So this implementation currently does the scan after the upload to Google Play.
> [#381] Scan release builds for malware

- .github/workflows/deploy.yml
This is a fix for a regression in the main branch deployment workflow https://github.com/zcash/secant-android-wallet/actions/runs/2669784435
> [#381] Fix workflow dependency for malware scan

- gradle/wrapper/gradle-wrapper.properties
> [#564] Gradle 7.5.1

- .github/workflows/pull-request.yml
- app/build.gradle.kts
- app/src/main/java/co/electriccoin/zcash/app/ZcashApplication.kt
- gradle.properties
- spackle-android-lib/src/main/kotlin/co/electriccoin/zcash/spackle/StrictModeCompat.kt
> [#560] Detect strict mode violations on CI

- app/src/androidTest/java/co/electriccoin/zcash/app/ScreenshotTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/MainActivity.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/Navigation.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/address/AndroidWalletAddresses.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/request/AndroidRequest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/scan/AndroidScan.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/seed/AndroidSeed.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/AndroidSend.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/update/AndroidUpdate.kt
This moves navigation to its own file, simplifies the MainActivity, and moves Android integration composables to their own files.
Navigation still does not have tests, so a separate change will need to be implemented to add testing to navigation.
> [#185] Refactor navigation

- app/build.gradle.kts
- build.gradle.kts
> Run robo test against API 33

- docs/testing/manual_testing/Screen brightness.md
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/common/ScreenBrightnessTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/profile/view/ProfileViewScreenBrightnessTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/MainActivity.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/ScreenBrightness.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/profile/view/ProfileView.kt
> [#167] Increase brightness when displaying QR Code

- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/common/ScreenTimeoutTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/profile/view/ProfileViewScreenTimeoutTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/MainActivity.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/CompositionLocalBinder.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/ScreenTimeout.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/profile/view/ProfileView.kt
> disabled screen timeout when displaying QR code

- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/onboarding/view/OnboardingViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/viewmodel/WalletViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/view/OnboardingView.kt
> fixed onboarding top bar

- app/build.gradle.kts
Explanation:
- Used re-running for the case of the robo test failure. We re-run the test only once to save time in case of another further problem.
- This solution can probably stay even after the real cause is found and solved as it saves us from flakiness of the test.
Closes https://github.com/zcash/secant-android-wallet/issues/645.
> [#645] Automated CameraX Robo test crash on CI

- docs/Setup.md
Closes https://github.com/zcash/secant-android-wallet/issues/649.
> [#649] Setup Included builds documentation update

- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/view/OnboardingView.kt
> fixed onboarding screen issues

- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/common/FlowExtTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/FlowExt.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/viewmodel/WalletViewModel.kt
> throttling wallet snapshot emits

- ui-screenshot-test/build.gradle.kts
- ui-screenshot-test/proguard-consumer.txt
Closes https://github.com/zcash/secant-android-wallet/issues/665.
> [#665] Gradle assemble task run fix

- ui-integration-test/src/main/java/co/electriccoin/zcash/ui/integration/test/screen/update/viewmodel/AppUpdateCheckerMock.kt
- Added small delays to the AppUpdateCheckerMock functions to copy a real-world situation a bit more
- This also helps with satisfying expectations in UpdateViewModelTest
> [#667] Fix for Update VM flaky test results

- gradle.properties
- sdk-ext-lib/src/androidTest/java/cash/z/ecc/sdk/model/WalletAddressesTest.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/SynchronizerExt.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/fixture/WalletAddressFixture.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/fixture/WalletAddressesFixture.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/model/SeedPhrase.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/model/WalletAddress.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/model/WalletAddresses.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/ExtendedColors.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/internal/Color.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/address/view/WalletAddressViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/ext/WalletAddressExtTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/global/WalletCoordinator.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/address/view/WalletAddressView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/model/CommonTransaction.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/view/HomeView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/viewmodel/WalletViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/AndroidSend.kt
- ui-lib/src/main/res/ui/wallet_address/values/strings.xml
- ui-screenshot-test/src/main/java/co/electroniccoin/zcash/ui/screenshot/ScreenshotTest.kt
Created just to start discussion on changes needed to adopt the new SDK 1.10.0 version.
Closes https://github.com/zcash/secant-android-wallet/issues/642.
> [#642] Adopt SDK 1.10.0 API changes

- .github/pull_request_template.md
> update of pr template v1

- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Chip.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreView.kt
- ui-lib/src/main/res/ui/restore/values/strings.xml
- ui-screenshot-test/src/main/java/co/electroniccoin/zcash/ui/screenshot/ScreenshotTest.kt
> [#600]Improve UX of wallet restore screen

- .idea/codeStyles/Project.xml
- ui-design-lib/build.gradle.kts
- ui-design-lib/src/androidTest/java/co/electriccoin/zcash/ui/design/component/ButtonTest.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Button.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/view/SendViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
> implementation of push and hold to send zec

- .github/workflows/deploy.yml
- .github/workflows/pull-request.yml
> [#699] Use new API for build step outputs

- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/fixture/WalletAddressFixture.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/model/WalletAddresses.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/profile/view/ProfileView.kt
- ui-screenshot-test/src/main/java/co/electroniccoin/zcash/ui/screenshot/ScreenshotTest.kt
> [#161] Implement display of new address types

- .github/workflows/pull-request.yml
- docs/CI.md
This will make it easier for team members to find links to test results
> **Note**
> **Note**
[^2]: _While we aim for automated testing of the application, some aspects …
> [#718] Use variables for Test Lab

- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/model/SeedPhrase.kt
> [#708] Fix seed byte generation

- ui-screenshot-test/src/main/java/co/electroniccoin/zcash/ui/screenshot/ScreenshotTest.kt
> Extend timeout for screenshot tests

- app/build.gradle.kts
- docs/testing/manual_testing/App Packaging.md
These files are used by Android Studio in debug builds to discover the version of Compose being used by an app.  They should be preserved for debug builds but can be stripped from release builds.
> **Note**
> **Note**
[^1]: _Code often looks different when reviewing the diff in a browser, …
> [#707] Exclude files from release packaging only

- gradle.properties
> [#725] SDK 1.12.0-beta01

- .github/workflows/pull-request.yml
- build.gradle.kts
- gradle.properties
> [#719] Check Gradle properties on CI

- .github/workflows/pull-request.yml
- build-conventions-secant/src/main/kotlin/secant.android-build-conventions.gradle.kts
- gradle.properties
We can leverage these metrics to improve our compose UI performance.
To test this, you can build the app and look under the build directory for the modules that use compose.  Alternatively, the CI job will also attach the metrics for the job called "build."
> **Note**
> **Note**
[^1]: …
> [#566] Enable Compose compiler metrics

- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/onboarding/OnboardingTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/onboarding/integration/OnboardingActivityTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/onboarding/integration/OnboardingIntegrationTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/onboarding/view/OnboardingViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/configuration/ConfigurationEntries.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/AndroidOnboarding.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/view/OnboardingView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/viewmodel/OnboardingViewModel.kt
- ui-screenshot-test/src/main/java/co/electroniccoin/zcash/ui/screenshot/ScreenshotTest.kt
> [#763] Configure simplified onboarding

- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/home/HomeTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/home/integration/HomeViewIntegrationTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/home/view/HomeViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/configuration/ConfigurationEntries.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/AndroidHome.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/HomeTag.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/view/HomeView.kt
> [#783] Hide fiat currency conversion

- .github/workflows/deploy.yml
- .github/workflows/pull-request.yml
- README.md
- app/build.gradle.kts
- build.gradle.kts
- docs/CI.md
- gradle.properties
- ui-lib/src/main/res/ui/support/values/strings.xml
This helps to ensure that any potential forks change the email and don’t accidentally include our email address
> **Note**
> **Note**
[^2]: _While we aim for automated testing …
> [#784] Refactor support email address to CI variable

- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/home/HomeTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/home/integration/HomeActivityTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/AndroidHome.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/HomeTag.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/view/HomeView.kt
Closes https://github.com/zcash/secant-android-wallet/issues/799.
> **Note**
> **Note** …
> [#799] Fix passing drawer state

- ui-design-lib/build.gradle.kts
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/SwitchWithLabel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/settings/view/SettingsView.kt
- SwitchWithLabel moved to `ui-design-lib`
- Internally switched from `Row` to `ConstraintLayout`
- Used paddings, which after creating and applying of Design system #611 will be refactored
- Moved Modifier definitions to the caller side, when possible
Closes https://github.com/zcash/secant-android-wallet/issues/790.
Before:
After:
Very long switch button text
> **Note**
> **Note**
> It is good practice to provide before and after UI …
> [#790] Fix Settings screen layout

- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/Dimens.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/ZcashTheme.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/internal/Dimens.kt
- Initial commit to ensure it meets our requirements
- This solution is now in parallel with a simpler existing Paddings solution
- Provides a way to define default and custom spacing values
- Could be distinguished by a screen size, but other metrics also available (e.g. orientation, aspect ratio, layout direction or screen shape)
Closes https://github.com/zcash/secant-android-wallet/issues/804.
> **Note**
> **Note**
> It is good practice to …
> [#804][Design system] Paddings - Dimens

- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Text.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/TextField.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/Dimens.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/ZcashTheme.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/internal/Dimens.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/settings/view/SettingsView.kt
- ui-lib/src/main/res/ui/send/values/strings.xml
- This task has these followups: https://github.com/zcash/secant-android-wallet/issues/809, https://github.com/zcash/secant-android-wallet/issues/810
- Closes https://github.com/zcash/secant-android-wallet/issues/789.
Before:
After:
> **Note**
> **Note**
[^1]: _Code often looks different …
> [#789] Fix Send Screen Layout

- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/fixture/PersistableWalletFixture.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/model/SeedPhraseValidation.kt
- ui-lib/build.gradle.kts
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreViewAndroidTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreViewSecuredScreenTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/AndroidOnboarding.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/AndroidRestore.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/RestoreTag.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/model/RestoreStage.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/state/RestoreState.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/state/WordList.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/viewmodel/RestoreViewModel.kt
- ui-lib/src/main/res/ui/restore/values/strings.xml
- ui-screenshot-test/src/main/java/co/electroniccoin/zcash/ui/screenshot/ScreenshotTest.kt
This is almost complete—I'm opening as a draft because I have a minor todo to fix with the layout to move the button to the bottom of the screen.  That shouldn't prevent us from moving forward with review though.
> **Note**
> **Note**
[^1]: _Code often looks different when reviewing the …
> [#151] Add birthday to restore

- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/home/HomeTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/home/integration/HomeActivityTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/home/integration/HomeViewIntegrationTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/home/view/HomeViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/configuration/ConfigurationEntries.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/AndroidHome.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/view/HomeView.kt
Closes https://github.com/zcash/secant-android-wallet/issues/786.
> **Note**
> **Note** …
> [#786] Hide circular progress bar on home screen

- README.md
> Remove link to ECC Wallet in readme

- gradle.properties
- ui-lib/src/main/java/co/electriccoin/zcash/ui/fixture/WalletSnapshotFixture.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/model/WalletDisplayValues.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/view/HomeView.kt
> Adopt SDK 1.17.0-beta01 changes

- build-conventions-secant/src/main/kotlin/secant.rosetta-conventions.gradle.kts
Closes https://github.com/zcash/secant-android-wallet/issues/877.
> **Note**
> **Note** …
> [#877] Fix Runtime.exec() in Rosetta build script

- tools/detekt-baseline.xml
- tools/detekt.yml
Closes https://github.com/zcash/secant-android-wallet/issues/888.
> **Note**
> **Note** …
> [#888] Remove Default Detekt Values

- sdk-ext-lib/src/androidTest/java/cash/z/ecc/sdk/type/ZcashCurrencyTest.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/model/ZecRequest.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/type/ZcashCurrency.kt
- This improvement will be useful for Zcash currency distinction while displaying wallet balances. 
- Closes https://github.com/zcash/secant-android-wallet/issues/891.
- And it has follow-up https://github.com/zcash/secant-android-wallet/issues/892.
> **Note**
> **Note**
[^1]: _Code often …
> [#891] ZEC/TAZ currency distinction

- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/receive/view/ReceiveViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreViewAndroidTest.kt
Closes https://github.com/zcash/secant-android-wallet/issues/897.
> **Note**
> **Note** …
> [#897] Fix failing keyboard_disappears_after_seed

- spackle-android-lib/src/main/kotlin/co/electriccoin/zcash/spackle/ClipboardManagerExt.kt
- spackle-android-lib/src/main/kotlin/co/electriccoin/zcash/spackle/ClipboardManagerUtil.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/address/view/WalletAddressViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/address/AndroidWalletAddresses.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/address/WalletAddressesTag.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/address/view/WalletAddressView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/backup/AndroidBackup.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/seed/AndroidSeed.kt
- ui-lib/src/main/res/ui/wallet_address/values/strings.xml
Closes https://github.com/zcash/secant-android-wallet/issues/905.
> **Note**
> **Note** …
> [#905] Add copy-to-clipboard for addresses

- build.gradle.kts
- gradle.properties
Closes https://github.com/zcash/secant-android-wallet/issues/925.
> **Note**
> **Note** …
> [#925] Rename app

- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Button.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Chip.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/TextField.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/backup/view/ChipDropDown.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/support/view/SupportView.kt
Closes https://github.com/zcash/secant-android-wallet/issues/914.
> **Note**
> **Note** …
> [#914] Rectangle shapes

- build.gradle.kts
- gradle.properties
Closes https://github.com/zcash/secant-android-wallet/issues/929.
> **Note**
> **Note** …
> [#929] Fill in support contact email

- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/internal/Color.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/support/view/SupportViewIntegrationTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/support/view/SupportViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/view/ShortOnboardingView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/support/view/SupportView.kt
- ui-lib/src/main/res/ui/common/values-night/colors.xml
- ui-lib/src/main/res/ui/common/values/colors.xml
- ui-lib/src/main/res/ui/support/values/strings.xml
- Simplified color model to just black and white colors
- Reworked send fab button to a regular primary button
- Closes https://github.com/zcash/secant-android-wallet/issues/915
> **Note**
> **Note**
[^1]: _Code often looks different when reviewing the diff in a browser, making it easier …
> [#915] Black and white color themes

- LICENSE
- docs/Third party licenses.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Chip.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Text.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/ZcashTheme.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/internal/Typography.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/backup/view/ChipDropDown.kt
- Font added
- License documentation file updated
- This slightly changes the provided font accessibility. Both Inter and Archivo are now available with the `ZcashTheme.typography` API.
- Closes #951
> **Note**
> **Note**
[^1]: _Code often looks different when reviewing the diff in a …
> [#951] Add Archivo font

- gradle.properties
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/fixture/PersistableWalletFixture.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/viewmodel/WalletViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/AndroidOnboarding.kt
Closes  #972.
> **Note**
> **Note** …
> [#972] Adopt PersistableWallet API changes in SDK

- .idea/codeStyles/Project.xml
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Button.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/ExtendedColors.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/internal/Color.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/internal/Typography.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/settings/SettingsViewTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/settings/fixture/TroubleshootingParametersFixture.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/settings/view/SettingsViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/settings/AndroidSettings.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/settings/SettingsTag.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/settings/model/TroubleshootingParameters.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/settings/view/SettingsView.kt
- ui-lib/src/main/res/ui/settings/values/strings.xml
Updated settings screen UI
**Ui Screenshots**
Before Changing UI
After changing UI
> **Note**
> **Note**
[^2]: _While we aim for automated testing of the application, some …
> [#948] Updated Settings screen UI

- ui-integration-test/src/main/java/co/electriccoin/zcash/ui/integration/test/screen/scan/view/ScanViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/backup/integration/BackupActivityTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/backup/integration/BackupIntegrationTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/backup/view/LongBackupViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/backup/view/ShortBackupViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/home/view/HomeViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/onboarding/integration/OnboardingActivityTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/onboarding/integration/OnboardingIntegrationTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/onboarding/view/LongOnboardingViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/onboarding/view/ShortOnboardingViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/receive/view/ReceiveViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/request/view/RequestViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/ComposeContentTestRuleExt.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/view/SendViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/settings/view/SettingsViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/support/view/SupportViewIntegrationTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/support/view/SupportViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/update/integration/UpdateViewIntegrationTest.kt
- ui-screenshot-test/src/main/java/co/electroniccoin/zcash/ui/screenshot/ScreenshotTest.kt
- Closes #985
> **Note**
> **Note** …
> [#985] Fix failing UI tests on texts' case

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- README.md
- All in-app strings were changed some time back. This PR changes repository documentation occurrences.
- Closes #977
> **Note**
> **Note**
[^2]: _While we aim for automated …
> [#977] Replace user-facing Secant with Zashi

- gradle.properties
Closes #980
> **Note**
> **Note** …
> [#980] Adopt SDK v2.0.1

- sdk-ext-lib/src/androidTest/java/cash/z/ecc/sdk/extension/PercentDecimalExtTest.kt
- sdk-ext-lib/src/androidTest/java/cash/z/ecc/sdk/model/ZecRequestTest.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/extension/PercentDecimalExt.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/extension/SynchronizerExt.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/model/WalletDisplayValues.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/view/HomeView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/AndroidSend.kt
- ui-lib/src/main/res/ui/home/values/strings.xml
Closes #974
> **Note**
> **Note** …
> [#974] Post SbS adoption UI changes

- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Button.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/about/view/AboutView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/address/view/WalletAddressView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/backup/view/LongNewWalletBackupView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/backup/view/ShortNewWalletBackupView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/history/view/HistoryView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/view/HomeView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/view/LongOnboardingView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/view/ShortOnboardingView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/receive/view/ReceiveView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/request/view/RequestView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/scan/view/ScanView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/seed/view/SeedView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/support/view/SupportView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/update/view/UpdateView.kt
- PrimaryButton centered horizontally on all screen
- Compose Preview switched to light theme on all screens as Zashi supports light theme only
- Closes #975
> **Note**
> **Note** …
> [#975] Post Core BTS UI changes

- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Button.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Checkbox.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/internal/Typography.kt
- ui-lib/build.gradle.kts
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/securitywarning/util/WebBrowserUtilTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/securitywarning/view/SecurityWarningViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/securitywarning/view/SecurityWarningViewTestSetup.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/MainActivity.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/preference/StandardPreferenceKeys.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/model/OnboardingState.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/viewmodel/WalletViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/AndroidOnboarding.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/view/LongOnboardingView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/securitywarning/AndroidSecurityWarning.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/securitywarning/util/WebBrowserUtil.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/securitywarning/view/SecurityScreenTag.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/securitywarning/view/SecurityWarningView.kt
- ui-lib/src/main/res/ui/onboarding/drawable/zashi_logo_without_text.xml
- ui-lib/src/main/res/ui/security_warning/values/strings.xml
- ui-screenshot-test/src/main/java/co/electroniccoin/zcash/ui/screenshot/ScreenshotTest.kt
- Closes #993 
- Closes #946
- New Primary Button Click Animation
- Security Warning screen incorporated into the app onboarding logic
- NeedsWarning wallet state persisted and is required if the user re-runs next time, and the Security Warning screen still needs to be presented
- Privacy Policy opened by part of the screen text clicking in an external web browser app
- Unit tests
- UI tests
- Screenshot tests
<br/><br/>
<br/><br/>
> **Note** …
> [#946][#993] Warning screen + button animation

- app/build.gradle.kts
- build.gradle.kts
- gradle.properties
- ui-design-lib/build.gradle.kts
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Button.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Checkbox.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Chip.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/ZcashTheme.kt
- ui-lib/build.gradle.kts
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/about/view/AboutView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/address/view/WalletAddressView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/backup/view/LongNewWalletBackupView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/backup/view/ShortNewWalletBackupView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/debug/view/DesignGuide.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/history/view/HistoryView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/view/HomeView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/view/LongOnboardingView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/view/ShortOnboardingView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/receive/view/ReceiveView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/request/view/RequestView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/scan/view/ScanView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/securitywarning/view/SecurityWarningView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/seed/view/SeedView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/settings/view/SettingsView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/support/view/SupportView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/update/view/UpdateView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/warning/view/NotEnoughSpaceView.kt
- And disable its support in the app UI by default for now
- Closes #1012
> **Note**
> **Note**
[^2]: _While we aim for automated testing of the application, some aspects …
> [#1012] Customize Dark mode support for debugging

- gradle.properties
Closes #1018
> **Note**
> **Note** …
> [#1018] Adopt SDK v2.0.2

- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/onboarding/ShortOnboardingTestSetup.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/AndroidOnboarding.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/view/LongOnboardingView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/view/ShortOnboardingView.kt
- The debug with Alice’s and Ben’s fixture wallets from the Zcash SDK is visible only in debug mode. UI tests and production are not impacted.
- It provides a quick way to import an existing wallet for developers while building or testing the app
- Closes #1020
- The debug menu with fixture wallet was partially hidden by PR #1004
<br/><br/>
> **Note**
> **Note**
> It is good practice to provide before and after UI  **screenshots** in the …
> [#1020] Re-enable fixture wallets in debug

- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/common/ScreenSecurityTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/seed/view/SeedViewSecuredScreenTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/ScreenSecurity.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/backup/view/LongNewWalletBackupView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/backup/view/ShortNewWalletBackupView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/seed/view/SeedView.kt
- After we added the customization of SecureScreen sensitive data mechanism in building and testing the app via Gradle property in #1009, we also need to ensure that the SecureScreen is always on in our automated Android UI tests.
- Closes #1016
> **Note**
> **Note**
[^1]: _Code often …
> [#1016] Force SecureScreen turned on in UI testing

- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreView.kt
- Closes #1026
- Now, it works as expected again. See video:
https://github.com/zcash/secant-android-wallet/assets/9017390/d0f060a1-6a2f-4ba1-8a30-f030d6e87a1d
> **Note**
> **Note** …
> [#1026] Fix Restore Seed screen keyboard hiding UI

- settings.gradle.kts
Closes #1023
> **Note**
> **Note** …
> [#1023] Remove zcash-android-wallet-plugins dependency

- build.gradle.kts
- gradle.properties
- ui-lib/build.gradle.kts
- ui-lib/src/main/java/co/electriccoin/zcash/ui/MainActivity.kt
- Adds capability to customize the screen lock via gradle.properties to enable it while developing or testing the app UI easily
- Closes #355
> **Note**
> **Note**
[^2]: …
> [#355] Lock screen to portrait

- .gitignore
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/history/view/HistoryView.kt
This change brings the Compose Preview to the Transaction History screen in a partly synced and found transactions state. 
> **Note**
> **Note**
[^2]: _While we aim for …
> [#998] Transaction History Compose Preview

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- build.gradle.kts
- gradle.properties
- ui-lib/build.gradle.kts
- ui-lib/src/androidTest/AndroidManifest.xml
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/fixture/MockSynchronizer.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/exportdata/util/FileShareUtilTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/exportdata/util/TestShareFileProvider.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/exportdata/view/ExportPrivateDataViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/exportdata/view/ExportPrivateDataViewTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/settings/SettingsViewTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/settings/view/SettingsViewTest.kt
- ui-lib/src/androidTest/res/ui/export_data/xml/share_file_provider_paths.xml
- ui-lib/src/main/AndroidManifest.xml
- ui-lib/src/main/java/co/electriccoin/zcash/ui/Navigation.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/exportdata/AndroidExportPrivateData.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/exportdata/util/FileShareUtil.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/exportdata/util/ShareFileProvider.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/exportdata/view/ExportPrivateDataScreenTag.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/exportdata/view/ExportPrivateDataView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/securitywarning/util/WebBrowserUtil.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/settings/AndroidSettings.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/settings/view/SettingsView.kt
- ui-lib/src/main/res/ui/common/values/strings.xml
- ui-lib/src/main/res/ui/export_data/values/strings.xml
- ui-lib/src/main/res/ui/export_data/xml/share_file_provider_paths.xml
- ui-lib/src/main/res/ui/new/values/strings.xml
- ui-lib/src/main/res/ui/security_warning/values/strings.xml
- ui-lib/src/main/res/ui/settings/values/strings.xml
- Contains  UI/logic/tests
- Uses updated SDK with the new Data database file path API
- Note that this wallet version depends on a `-SNAPSHOT` version of the SDK as it waits for v2.0.3 availability, but it's saved to use the SNAPSHOT version.  
- One of the tets is disabled, and follow-up is filed #1034
- Closes #1031
> **Note**
> **Note**
> It is good practice to provide before and after UI  **screenshots** in the description of this PR. …
> [#1031] Export of private app data

- app/src/debug/AndroidManifest.xml
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/exportdata/util/FileShareUtilTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/exportdata/AndroidExportPrivateData.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/exportdata/util/FileShareUtil.kt
- Both debug and production builds of the app can now be deployed on the same device
- Closes #1051
> **Note**
> **Note**
[^2]: _While we aim for automated testing of the …
> [#1051] Fix Export Data FileProvider

- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Button.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/Dimens.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/about/view/AboutView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/debug/view/DesignGuide.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/exportdata/view/ExportPrivateDataView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/view/HomeView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/newwalletrecovery/view/NewWalletRecoveryView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/view/ShortOnboardingView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/receive/view/ReceiveView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/request/view/RequestView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/scan/view/ScanView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/securitywarning/view/SecurityWarningView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/seedrecovery/view/SeedRecoveryView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/settings/view/SettingsView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/support/view/SupportView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/update/view/UpdateView.kt
- ui-lib/src/main/res/ui/wallet_address/values/strings.xml
- Done across all screens
- Closes #1054
- Closes #1055
> **Note**
> **Note**
[^2]: _While we aim for automated testing of the application, some aspects require manual …
> [#1054][#1055] Update buttons and screens spacings

- CHANGELOG.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Button.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Chip.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/ChipGrid.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/Dimens.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/ExtendedColors.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/internal/Color.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/internal/Typography.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/debug/view/DesignGuide.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/model/ParseResult.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/state/WordList.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreView.kt
- ui-lib/src/main/res/ui/restore/values/strings.xml
- ui-screenshot-test/src/main/java/co/electroniccoin/zcash/ui/screenshot/ScreenshotTest.kt
- Reworked UI according to Figma design
- The previous version used a separate `Textfield` with `ChipGrid`. The new solution works with improved `TextFiled` only
- Closes #1059
- Closes #347 
https://github.com/Electric-Coin-Company/zashi-android/assets/9017390/5b235415-594e-4494-b0e5-00e069ea4ddb
> **Note**
> **Note**
> It is good practice to provide before and after UI  **screenshots** in the description of this PR. This is only applicable …
> [#1059] Restore Seed Screen

- CHANGELOG.md
- Closes #1080
> **Note**
> **Note** …
> [#1080] Release v0.2.0 (491)

- docs/Setup.md
- docs/Sideloading.md
- This PR excludes the wallet app's APK sideloading into a separate documentation file. It preserves the Android Studio installation description and adds the Android SDK installation path instructions, which require less disk space and are used within the command line.
- The command line tools path tested on a clear macOS installation
- Closes #1069
> **Note**
> **Note**
> It is good practice to provide before and after UI  **screenshots** in …
> [#1069] Improve sideloading documentation

- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/home/HomeTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/home/integration/HomeViewIntegrationTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/home/view/HomeViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/configuration/ConfigurationEntries.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/AndroidHome.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/HomeTag.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/view/HomeView.kt
Closes #1089
> **Note**
> **Note** …
> [#1089] Remove circular progress bar from Home

- CHANGELOG.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/Navigation.kt
- ui-lib/src/main/res/ui/common/values/strings.xml
- Closes #1094
- Shows Toast UI message with Not implemented yet test after the buttons hit
> **Note**
> **Note**
[^2]: _While we aim for automated testing of the application, …
> [#1094] Add message under Doc and PP buttons

- CHANGELOG.md
Closes #1114
> **Note**
> **Note** …
> [#1114] Release v0.2.0 (505)

- CHANGELOG.md
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/ComposeContentTestRuleExt.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/SendViewTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/integration/SendViewIntegrationTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/view/SendViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
Closes #1121
> **Note**
> **Note** …
> [#1121] Available balance check on Send

- CHANGELOG.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/TextField.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/Dimens.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/about/view/AboutView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/view/AccountView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/view/BalancesView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/exportdata/view/ExportPrivateDataView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/view/HomeView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/newwalletrecovery/view/NewWalletRecoveryView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/view/OnboardingView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/receive/view/ReceiveView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/request/view/RequestView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/scan/view/ScanView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/securitywarning/view/SecurityWarningView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/seedrecovery/view/SeedRecoveryView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/settings/view/SettingsView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/support/view/SupportView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/update/view/UpdateView.kt
- Improved Home subscreens paddings
- Reworked Home Scaffold to ConstraintLayout
- Reworked Send screen TextFields navigation and screen auto-scrolling behaviour with respect the the current time state
- Plus, unify the Home sub-screens bottom action buttons' position
- Closes #1134
> **Note**
> **Note**
> It is good practice to provide before and after UI  **screenshots** in the description of this PR. This is only applicable for changes …
> [#1134] Home screens UI improvements

- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/extension/PercentDecimalExt.kt
- This handles possible malformed format pattern exceptions in Zashi, but the proper solution needs to be provided within the SDK. See  #1315.
- Closes #1139
> **Note**
> **Note** …
> [#1139] Malformed pattern for ICU DecimalFormat

- CHANGELOG.md
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/extension/PercentDecimalExt.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
- This handles possible malformed format pattern exceptions in Zashi, but the proper solution needs to be provided within the SDK. See  #1315.
- Closes #1138
> **Note**
> **Note** …
> [#1138] Malformed pattern: Grouping separator

- CHANGELOG.md
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/extension/PercentDecimalExt.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
Closes #1136
> **Note**
> **Note** …
> [#1136] Release v0.2.0 (517)

- CHANGELOG.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Text.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/history/HistoryTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/history/view/HistoryViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/AndroidAccount.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/address/AndroidWalletAddresses.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/exportdata/AndroidExportPrivateData.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/history/AndroidHistory.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/history/HistoryTag.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/history/view/HistoryView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/view/HomeView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/receive/AndroidReceive.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/request/AndroidRequest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/scan/AndroidScan.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/seedrecovery/AndroidSeedRecovery.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/AndroidSend.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/settings/AndroidSettings.kt
- ui-lib/src/main/res/ui/history/values/strings.xml
- Improves the screen UI so we’re able to click on history items, and query transaction memos
- These APIs will be useful once we approach screen refactoring according to the Figma design
- Adds UI test for the new feature
- Closes #1147
https://github.com/Electric-Coin-Company/zashi-android/assets/9017390/a4c75c65-e985-41ea-8d03-c8576443aee9
> **Note**
> **Note**
> It is good practice to provide before and after UI  **screenshots** in the …
> [#1147] Show transaction memo

- CHANGELOG.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Text.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/history/HistoryTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/history/view/HistoryViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/history/AndroidHistory.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/history/HistoryTag.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/history/view/HistoryView.kt
- ui-lib/src/main/res/ui/history/values/strings.xml
- Added a new transaction ID row into the transaction item on the Transactions screen
- It displays a TODO value instead of the TXID until the #1316 in SDK done
- Closes #1143
https://github.com/Electric-Coin-Company/zashi-android/assets/9017390/b3cb31c5-8a35-4b35-9b4d-e5ee2871aadd
> **Note**
> **Note**
> It is good practice to provide before and after UI  **screenshots** in the description of this PR. This is only applicable for changes that …
> [#1143] Transaction ID row in Transaction item

- CHANGELOG.md
- gradle.properties
- sdk-ext-lib/src/androidTest/java/cash/z/ecc/sdk/extension/PercentDecimalExtTest.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/extension/LightWalletEndpointDefaultExt.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/extension/PercentDecimalExt.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/fixture/PersistableWalletFixture.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/WalletViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/model/WalletDisplayValues.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/history/view/HistoryView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/AndroidOnboarding.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/request/view/RequestView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/support/model/EnvironmentInfo.kt
- Closes #1153
- These changes leverage the `TransactionOverview.txIdString()` and  `MonetarySeparators.current(Locale)` SDK's APIs.
> **Note**
> **Note**
[^2]: _While we aim …
> [#1153] Adopt SDK v2.0.4

- CHANGELOG.md
- Closes #1174
- Changelog updated
> **Note**
> **Note** …
> [1174] Release v0.2.0 (523)

- CHANGELOG.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/warning/view/NotEnoughSpaceView.kt
- ui-lib/src/main/res/ui/warning/values/strings.xml
- Closes #883
- This removes the hardcoded dark theme from the NotEnoughSpace screen
- Note that this screen does not have its design aligned with the current Figma, as the design is not ready yet 
> **Note**
> **Note**
[^1]: _Code often looks different when reviewing the diff in a …
> [#883] Turn on NotEnoughSpace light theme

- CHANGELOG.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Button.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/update/util/AppUpdateCheckerImpTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/update/view/UpdateViewAndroidTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/update/view/UpdateViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/update/AppUpdateCheckerImp.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/update/view/UpdateView.kt
- ui-lib/src/main/res/ui/update/values/strings.xml
- Closes #1178
- The App Update screen's user interface was improved to align with the other implemented screens. Its final design 
is still in progress.
> **Note**
> **Note** …
> [#1178] Slightly improve Update screen UI

- CHANGELOG.md
- Closes #1188
> **Note**
> **Note** …
> [#1188] Release v0.2.0 (530)

- CHANGELOG.md
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/fixture/ZecSendFixture.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/ComposeContentTestRuleExt.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/SendViewTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/integration/SendViewIntegrationTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/view/SendViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/model/WalletDisplayValues.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/view/AccountView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/AndroidHome.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/AndroidSend.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
- ui-lib/src/main/res/ui/send/values/strings.xml
- Closes #1195
- The fixture recipient address type changed from the unified to the sapling on several tests to avoid temporary address TODO text obtained from the SDK fixture
- WalletDisplayValues have the updateAvailable optional with false as a default value
- Changelog updated
> **Note**
> **Note**
> It is good practice to provide before and after UI  **screenshots** in the description of this PR. This is only applicable for changes that …
> [#1195] Integrate Current Balances widget to Send

- CHANGELOG.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/AndroidBalances.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/view/BalancesView.kt
- ui-lib/src/main/res/ui/balances/values/strings.xml
- ui-screenshot-test/src/main/java/co/electroniccoin/zcash/ui/screenshot/ScreenshotTest.kt
- Closing #1196
> **Note**
> **Note** …
> [#1196] Balances widget on Balances screen

- CHANGELOG.md
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/SendViewTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/integration/SendViewIntegrationTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/AndroidBalances.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/view/BalancesView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/view/HomeView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/AndroidSend.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
- ui-lib/src/main/res/ui/balances/values/strings.xml
- ui-screenshot-test/src/main/java/co/electroniccoin/zcash/ui/screenshot/ScreenshotTest.kt
- Closes #1206
> **Note**
> **Note** …
> [#1206] Clear focus on Send Form

- CHANGELOG.md
Closes #1208
> **Note**
> **Note** …
> [#1208] Release 0.2.0 (540)

- CHANGELOG.md
- gradle.properties
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/ext/WalletAddressExtTest.kt
Closing #1210
> **Note**
> **Note** …
> [#1210] Release 0.2.0 (541)

- gradle.properties
- Closes #1212
> **Note**
> **Note** …
> [#1212] Adopt Zcash SDK 2.0.6

- CHANGELOG.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Text.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/internal/Typography.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/BalanceWidget.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/receive/view/ReceiveView.kt
> [#1032] Prevent font ligatures on addresses

- CHANGELOG.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Text.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/view/HomeView.kt
Closing #1216
> **Note**
> **Note** …
> [#1216] Home screen tabs UI improvements

- CHANGELOG.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Progress.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Text.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/Dimens.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/ExtendedColors.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/internal/Color.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/account/view/AccountViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/balances/BalancesTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/balances/integration/BalancesViewIntegrationTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/balances/model/WalletDisplayValuesTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/balances/view/BalancesViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/AccountTag.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/AndroidAccount.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/view/AccountView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/AndroidBalances.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/BalancesTag.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/model/WalletDisplayValues.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/view/BalancesView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
- ui-lib/src/main/res/ui/account/values/strings.xml
- ui-lib/src/main/res/ui/balances/values/strings.xml
- ui-screenshot-test/src/main/java/co/electroniccoin/zcash/ui/screenshot/ScreenshotTest.kt
-  UI + logic + tests
- Closes  #1165
> **Note**
> **Note** …
> [#1165] Syncing progressbar

- CHANGELOG.md
Closes #1245
> **Note**
> **Note** …
> [#1245] Release 0.2.0 (554)

- CHANGELOG.md
Closes #1267
> **Note**
> **Note** …
> [#1267] Release 0.2.0 (560)

- CHANGELOG.md
- ui-lib/build.gradle.kts
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/settings/SettingsViewTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/settings/view/SettingsViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/Navigation.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/advancedsettings/AdvancedSettingsTag.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/advancedsettings/AndroidAdvancedSettings.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/advancedsettings/view/AdvancedSettingsView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/settings/AndroidSettings.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/settings/view/SettingsView.kt
- ui-lib/src/main/res/ui/advanced_settings/values/strings.xml
- ui-lib/src/main/res/ui/settings/values/strings.xml
- ui-screenshot-test/src/main/java/co/electroniccoin/zcash/ui/screenshot/ScreenshotTest.kt
- Closes #1234
> **Note**
> **Note** …
> [#1234] Advanced settings screen

- CHANGELOG.md
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/extension/LightWalletEndpointExt.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Button.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/RadioButton.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/TextField.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/ExtendedColors.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/internal/Color.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/internal/Typography.kt
- ui-lib/build.gradle.kts
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/fixture/MockSynchronizer.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/Navigation.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/WalletViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/chooseserver/AndroidChooseServer.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/chooseserver/AvailableServerProvider.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/chooseserver/ChooseServerTag.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/chooseserver/view/ChooseServerView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreView.kt
- ui-lib/src/main/res/ui/advanced_settings/values/strings.xml
- ui-lib/src/main/res/ui/choose_server/values/strings.xml
- Closes #1235
- Note that failures and server saving success are reported to the UI with the Android system Snackbar or via the existing Textfield’s error bottom text until we define popup design as filed in #1242
https://github.com/Electric-Coin-Company/zashi-android/assets/9017390/c09462aa-e8c3-4e5a-90c7-b2df4a19feb9
> **Note**
> **Note**
> It is good practice to provide before and after UI  **screenshots** in the …
> [#1235] Server switching

- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Dialog.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/TextField.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/balances/BalancesTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/support/view/SupportViewIntegrationTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/support/view/SupportViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/support/view/SupportViewTestSetup.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/AndroidBalances.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/view/BalancesView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/chooseserver/AndroidChooseServer.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/chooseserver/AvailableServerProvider.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/chooseserver/view/ChooseServerView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/AndroidSend.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/support/AndroidSupport.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/support/view/SupportView.kt
- ui-lib/src/main/res/ui/balances/values/strings.xml
- ui-lib/src/main/res/ui/choose_server/values/strings.xml
- ui-lib/src/main/res/ui/send/values/strings.xml
- ui-lib/src/main/res/ui/support/values/strings.xml
- Closes #1242
- This creates a reusable alert dialog UI and uses it in the server switching, shielding transparent funds, and contacting support use cases.
- This also updates the Transparent funds shielding help text according to the latest design guideline
> **Note**
> **Note**
[^1]: …
> [#1242] Unified error popup UI

- CHANGELOG.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/internal/Typography.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/about/util/WebBrowserUtilTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/about/view/AboutViewTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/securitywarning/view/SecurityWarningViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/securitywarning/view/SecurityWarningViewTestSetup.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/about/AndroidAboutView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/about/util/WebBrowserUtil.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/about/view/AboutTag.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/about/view/AboutView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/securitywarning/AndroidSecurityWarning.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/securitywarning/view/SecurityScreenTag.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/securitywarning/view/SecurityWarningView.kt
- ui-lib/src/main/res/ui/about/values/strings.xml
- ui-lib/src/main/res/ui/security_warning/values/strings.xml
- Closes #1262
- Closes #1083
- Closes #1241
> **Note**
> **Note**
[^2]: _While we aim for automated testing of the application, some aspects require manual testing. If you …
> [#1262][#1083][#1241] Privacy policy link

- CHANGELOG.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Button.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/Dimens.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/internal/Typography.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/view/BalancesView.kt
- Applied to both Primary and secondary buttons
- Closes #1280
> **Note**
> **Note**
[^2]: _While we aim for automated testing of the application, some aspects require manual …
> [#1280] Improve button sizing

- CHANGELOG.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/ChipGrid.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/newwalletrecovery/view/NewWalletRecoveryTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/newwalletrecovery/view/NewWalletRecoveryViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/newwalletrecovery/view/NewWalletRecoveryViewsSecuredScreenTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/seedrecovery/view/SeedRecoveryTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/seedrecovery/view/SeedRecoveryViewTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/seedrecovery/view/SeedRecoveryViewsSecuredScreenTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/newwalletrecovery/AndroidNewWalletRecovery.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/newwalletrecovery/view/NewWalletRecoveryView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/seedrecovery/AndroidSeedRecovery.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/seedrecovery/view/SeedRecoveryTag.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/seedrecovery/view/SeedRecoveryView.kt
- New wallet screen: Copy seed only in debug
- Seed screen: Copy seed only in debug
- Tests updated
- Closes #1286 
> **Note**
> **Note**
[^2]: _While we …
> [#1286] Remove Seed Copy Button

- CHANGELOG.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Button.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/SendViewTestSetup.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/AndroidBalances.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/AndroidSend.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/sendconfirmation/AndroidSendConfirmation.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/sendconfirmation/view/SendConfirmationView.kt
- Closes #1161
> **Note**
> **Note** …
> [#1161] Remove Send.Success + rework Send.Failure

- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/extension/FlowExt.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/sendconfirmation/AndroidSendConfirmation.kt
Closes #1303
> **Note**
> **Note** …
> [#1303] Refresh transactions immediately

- ui-lib/src/main/java/co/electriccoin/zcash/ui/Navigation.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/AndroidBalances.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/AndroidHome.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/sendconfirmation/AndroidSendConfirmation.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/sendconfirmation/model/SendConfirmationArguments.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/sendconfirmation/model/SendConfirmationStage.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/sendconfirmation/view/SendConfirmationView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/sendconfirmation/viewmodel/CreateTransactionsViewModel.kt
- Closes #1305
> **Note**
> **Note** …
> [#1305] Connect shielding Multi-Trx-Submit-Error

- .gitignore
- CHANGELOG.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Progress.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/Dimens.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/account/AccountTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/account/history/HistoryTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/account/history/fixture/TransactionHistorySyncStateFixture.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/account/history/fixture/TransactionHistoryUiStateFixture.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/account/history/view/HistoryViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/WalletViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/AndroidAccount.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/ext/TransactionOverviewExt.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/model/HistoryItemExpandableState.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/model/TransactionUi.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/model/TransactionUiState.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/state/TransactionHistorySyncState.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/view/AccountView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/view/HistoryView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/viewmodel/TransactionHistoryViewModel.kt
- ui-lib/src/main/res/ui/account/values/strings.xml
- Closes #1307
- #1162 is the direct follow-up of this PR
> **Note**
> **Note**
[^2]: _While we aim for automated testing of the application, some aspects …
> [#1307] Keep transaction history UI state

- CHANGELOG.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/view/HistoryView.kt
Closes #1310
> **Note**
> **Note** …
> [#1310] Release 0.2.0 (583)

- CHANGELOG.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Dialog.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/view/BalancesView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/chooseserver/view/ChooseServerView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/sendconfirmation/view/SendConfirmationView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/sendconfirmation/viewmodel/CreateTransactionsViewModel.kt
- Closes #1312
- Changelog reverter as the previous release hasn’t been deployed yet due to a new bug
- Note the SDK errors are not localized, filed #1276
> **Note**
> **Note** …
> [#1312] Display SDK error cause in dialog

- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/model/WalletSnapshot.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
- Closes #1317
> **Note**
> **Note** …
> [#1317] Improve balances logic calculation

- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Button.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/AndroidBalances.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/model/ShieldState.kt
- ui-lib/src/main/res/ui/balances/values/strings.xml
- This adds `ShieldState.Shielded` that helps us keep the correct UI state of the Transparent funds widget after the user starts shielding action
- This also brings little UI improvement in PrimaryButton sizing
> **Note**
> **Note**
[^1]: _Code often looks different when reviewing the …
> Extend shielding state

- CHANGELOG.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Progress.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/Dimens.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/ExtendedColors.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/internal/Color.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/account/AccountTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/balances/BalancesTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/SendViewTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/integration/SendViewIntegrationTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/compose/BalanceWidget.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/WalletViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/fixture/BalanceStateFixture.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/AndroidAccount.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/view/AccountView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/AndroidBalances.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/view/BalancesView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/AndroidSend.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
- Closes #1264
> **Note**
> **Note** …
> [#1264] Handle unavailable AccountBalance

- CHANGELOG.md
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/balances/BalancesTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/balances/model/WalletDisplayValuesTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/HomeViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/preference/StandardPreferenceKeys.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/AndroidBalances.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/model/WalletDisplayValues.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/view/BalancesView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/AndroidHome.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreView.kt
- ui-lib/src/main/res/ui/balances/values/strings.xml
- Closes #1263
> **Note**
> **Note** …
> [#1263] Statuses of the sync process

- CHANGELOG.md
- gradle.properties
- Closes #1328
> **Note**
> **Note** …
> [#1328] Release 0.2.0 (593)

- CHANGELOG.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/model/WalletDisplayValues.kt
> Release 0.2.0 (594)

- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/sendconfirmation/viewmodel/CreateTransactionsViewModel.kt
> Fix shielding state interpretation

- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/HomeViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/preference/StandardPreferenceKeys.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/AndroidHome.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/view/HomeView.kt
> Show initial restoring dialog

- .github/workflows/deploy.yml
> Document encoding of the upload key for Github secrets in deploy action

- settings.gradle.kts
- Closes #1354
- The repository regex changed to align with audit findings and still be able to cover both com.android:signflinger:[version] and com.android.tools:common:[version]
> **Note**
> **Note**
[^1]: _Code often looks different when reviewing the diff in a browser, making it …
> [#1354] Repository restriction regex

- crash-android-lib/src/main/kotlin/co/electriccoin/zcash/crash/android/internal/firebase/FirebaseCrashReporter.kt
- Although GlobalCrashReporter is built primarily as an interface for the locale exceptions reporting using LocalCrashReporter, the FirebaseCrashReporter inherits its reportCaughtException API and provides the ability to report a caught exception to remote crashyltics service. This commit disables this API for FirebaseCrashReporter.
- Closes #1356
> **Note**
> **Note**
> It is good practice to provide before and after UI  **screenshots** in …
> [#1356] Do not report caught exceptions

- CHANGELOG.md
Closes #1361
> **Note**
> **Note** …
> [#1361] Release 0.2.0 (609)

- CHANGELOG.md
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/SendViewTestSetup.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/AndroidSend.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/model/AmountState.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
- Closes #1367
- Plus slightly refactored SendForm composable to two functions
> **Note**
> **Note**
[^2]: _While we aim for automated testing of the application, some aspects …
> [#1367] Send 0 funds only within shielded trans

- CHANGELOG.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/model/WalletSnapshot.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/WalletViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/view/BalancesView.kt
- Closes #1371
- This also covers the security audit recommendation: 4.2.14 (App) This comment in WalletSnapshot.kt should be ticketed
> **Note**
> **Note**
[^2]: _While we …
> [#1371] Improve Balances widget loader logic

- configuration-api-lib/src/commonMain/kotlin/co/electriccoin/zcash/configuration/api/MergingConfigurationProvider.kt
- configuration-api-lib/src/commonMain/kotlin/co/electriccoin/zcash/configuration/model/entry/BooleanConfigurationEntry.kt
- configuration-api-lib/src/commonMain/kotlin/co/electriccoin/zcash/configuration/model/entry/IntegerConfigurationEntry.kt
- configuration-api-lib/src/commonMain/kotlin/co/electriccoin/zcash/configuration/model/exception/ConfigurationParseException.kt
- configuration-api-lib/src/commonMain/kotlin/co/electriccoin/zcash/configuration/model/map/StringConfiguration.kt
- configuration-api-lib/src/commonTest/kotlin/co/electriccoin/zcash/configuration/test/MockConfiguration.kt
- Closes #1372
- Follow up #1373
> **Note**
> **Note** …
> [#1372] Throw if parsing configuration failed

- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/view/BalancesView.kt
- ui-lib/src/main/res/ui/balances/values/strings.xml
Closes #1291
> **Note**
> **Note** …
> [#1291] Balances hint box copy update

- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/util/ScreenHeight.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/view/OnboardingView.kt
- Closes #372
- All screens were checked
- The Onboarding screen behavior on very small screens improved
- Tested with Split screen OS feature to emulate a very small screen
> **Note**
> **Note**
[^1]: _Code often looks different when reviewing the diff in a browser, making it easier to …
> [#372] Improve scrolling on Onboarding

- CHANGELOG.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
> Scroll to Send button

- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/view/BalancesView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
- The proper solution will be added with #1047
> **Note**
> **Note**
[^2]: _While we aim for automated testing of the application, some aspects require manual testing. If you …
> Display max three decimals within the fee amount

- gradle.properties
Closes #1391
> **Note**
> **Note** …
> [#1391] Adopt SDK production v2.1.1

- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/chooseserver/AvailableServerProvider.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/chooseserver/view/ChooseServerView.kt
- 8 more servers added to the list
- Order of servers changed to show default as 1st, custom as 2nd
> **Note**
> **Note**
[^2]: _While we aim for automated testing of the …
> Add more servers to the list

- CHANGELOG.md
Closes #1395
> **Note**
> **Note** …
> [#1395] Release Zashi Android version 1.0 (630)

- CHANGELOG.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/WalletViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/chooseserver/AvailableServerProvider.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/chooseserver/view/ChooseServerView.kt
- Default wallet option changed to zec.rocks:443
- Changleog update
> **Note**
> **Note** …
> Add zec.rocks lightwalletd server options

- CHANGELOG.md
- Closes #1402 
> **Note**
> **Note** …
> [#1402] Release version 1.0 (636)

- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/extension/LightWalletEndpointExt.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/AndroidOnboarding.kt
> Fix server selection in Restore wallet flow

- CHANGELOG.md
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/extension/LightWalletEndpointExt.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/AndroidOnboarding.kt
- Closes #1405
> **Note**
> **Note** …
> [#1405] Release version 1.0 (638)

- CHANGELOG.md
- gradle.properties
- preference-api-lib/src/commonMain/kotlin/co/electriccoin/zcash/preference/api/PreferenceProvider.kt
- preference-api-lib/src/commonTest/kotlin/co/electriccoin/zcash/preference/test/MockPreferenceProvider.kt
- preference-impl-android-lib/src/main/java/co/electriccoin/zcash/preference/AndroidPreferenceProvider.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/internal/Typography.kt
- ui-lib/build.gradle.kts
- ui-lib/src/main/java/co/electriccoin/zcash/ui/Navigation.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/WalletViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/advancedsettings/AndroidAdvancedSettings.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/advancedsettings/view/AdvancedSettingsView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/deletewallet/AndroidDeleteWallet.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/deletewallet/view/DeleteWalletView.kt
- ui-lib/src/main/res/ui/advanced_settings/values/strings.xml
- ui-lib/src/main/res/ui/delete_wallet/values/strings.xml
- Closes #1407
> **Note**
> **Note** …
> [#1407] Add Delete wallet feature

- CHANGELOG.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/WalletViewModel.kt
- Closes #1425
> **Note**
> **Note** …
> [#1425] Improve Balances widget loader logic

- CHANGELOG.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/view/HistoryView.kt
- Closes #1427
> **Note**
> **Note** …
> [#1427] Do not concatenate memos

- CHANGELOG.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/view/HistoryView.kt
- Closes #1429
> **Note**
> **Note** …
> [#1429] Deduplicate messages on transaction

- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/internal/Typography.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/account/history/fixture/TransactionHistorySyncStateFixture.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/WalletViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/ext/TransactionOverviewExt.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/fixture/TransactionUiFixture.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/model/TransactionUi.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/view/HistoryView.kt
- ui-lib/src/main/res/ui/account/values/strings.xml
- Closes #1350
> **Note**
> **Note** …
> [#1350] No message included in transaction

- CHANGELOG.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/about/view/AboutView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/view/HistoryView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/support/model/OperatingSystemInfo.kt
- ui-lib/src/main/res/ui/restore/values/strings.xml
- Closes #1431
- Account - syncing bar vertical paddings too big
- Add missing bottom padding on About
- Improve OS info in the support email template
- [#1348] Update restore wallet text field copy
> **Note**
> **Note**
[^1]: _Code often looks different when reviewing …
> [#1431] Minor UI improvements

- CHANGELOG.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/util/ScreenHeight.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/onboarding/view/OnboardingViewTest.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/view/OnboardingView.kt
- Closes #1382
> **Note**
> **Note** …
> [#1382] Improve Onboarding screen dynamic height calculation

- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/WalletViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/deletewallet/AndroidDeleteWallet.kt
- This improves internal app state resetting
- And adds a better UX by relaunching the Onboarding screen enter animation 
> **Note**
> **Note**
[^2]: _While we aim for …
> Delete wallet feature improvement

- CHANGELOG.md
- gradle.properties
Closes #1451
> **Note**
> **Note** …
> [#1451] Release Zashi Android version 1.1 (655)

- CHANGELOG.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/WalletViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/AndroidBalances.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/AndroidHome.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/sendconfirmation/AndroidSendConfirmation.kt
- Closes #1456
- Also, these changes leverage updated snapshot Zcash SDK version  2.1.2
> **Note**
> **Note**
[^2]: _While we aim for automated testing of …
> [#1456] runCreateTransactions on lifecycleScope

- CHANGELOG.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/Navigation.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/WalletViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/ext/TransactionOverviewExt.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/disconnected/AndroidDisconnected.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/disconnected/model/DisconnectedUiState.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/disconnected/view/DisconnectedView.kt
- ui-lib/src/main/res/ui/common/values/strings.xml
- Closes #1458
- Provide unsorted trx list when disconnected: These changes also improve the app’s ability to use the SDK’s APIs to provide a transaction history list, even in a disconnected state. In such a case, the list is sorted by its original order.
> **Note**
> **Note**
> It is good practice to provide before and after UI  **screenshots** in the description of this PR. This is only applicable for changes that modify …
> [#1458] Detect unavailable service and show a dialog

- CHANGELOG.md
- gradle.properties
Closes #1465
> **Note**
> **Note** …
> Release Zashi Android version 1.1.1 (660)

- CHANGELOG.md
- gradle.properties
Closes #1480
> **Note**
> **Note** …
> [#1480] Release Zashi Android version 1.1.2 (671)

- build.gradle.kts
- gradle.properties
- ui-design-lib/build.gradle.kts
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/ZcashTheme.kt
Closes #1483
> **Note**
> **Note** …
> [#1483] Remove dev condition for dark mode

- CHANGELOG.md
Closes #1485 
> **Note**
> **Note** …
> [#1480] Release Zashi Android version 1.1.2 (673)

- .gitignore
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Button.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/theme/internal/ButtonColors.kt
Closes #1487
> **Note**
> **Note** …
> [#1487] Change Tertiary button disable color

- README.md
- app/proguard-project.txt
- settings.gradle.kts
Closes #96
> **Note**
> **Note** …
> #96 Release build R8 warnings

- CHANGELOG.md
Closes #1489
> **Note**
> **Note** …
> [#1489] Release Zashi Android version 1.1.2 (676)

- CHANGELOG.md
- sdk-ext-lib/src/androidTest/java/cash/z/ecc/sdk/extension/ZatoshiExtTest.kt
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/extension/ZatoshiExt.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Balance.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Text.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/compose/BalanceWidget.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/extension/ZecAmountExt.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/model/TrxItemState.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/view/HistoryView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/view/BalancesView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/sendconfirmation/view/SendConfirmationView.kt
- ui-lib/src/main/res/ui/common/values/strings.xml
- ui-lib/src/main/res/ui/onboarding/values/strings.xml
- Closes #1047
- Tests
> **Note**
> **Note**
[^2]: _While we aim for automated testing of the application, some aspects require manual testing. If you had …
> [#1047] Consistent Zatoshi amounts representation

- CHANGELOG.md
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/SendViewTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/integration/SendViewIntegrationTest.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/update/view/UpdateViewAndroidTestSetup.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/Navigation.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/compose/CompositionLocalBinder.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/compose/LocalActivity.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/compose/LocalNavController.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/HomeViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/about/AndroidAboutView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/AndroidAccount.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/AndroidBalances.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/exportdata/AndroidExportPrivateData.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/AndroidHome.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/view/HomeView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/newwalletrecovery/AndroidNewWalletRecovery.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/AndroidOnboarding.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/receive/AndroidReceive.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/scan/AndroidScan.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/scan/view/ScanView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/securitywarning/AndroidSecurityWarning.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/seedrecovery/AndroidSeedRecovery.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/AndroidSend.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/settings/AndroidSettings.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/support/AndroidSupport.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/update/AndroidUpdate.kt
Closes #814
> **Note**
> **Note** …
> #814 Compose back handler

- CHANGELOG.md
- gradle.properties
> [#1500] Release Zashi Android version 1.1.3 (682)

- .gitignore
- .idea/vcs.xml
Added .idea/csv-editor.xml and .idea/vcs.xml to .gitgnore. It's not necessary to share these files and they very often are updated by AS automatically.
> .gitignore update

- CHANGELOG.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Balance.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/compose/BalanceWidget.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/view/HistoryView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/view/BalancesView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/sendconfirmation/view/SendConfirmationView.kt
Closes #1499
[^4]: _Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) …
> [#1499] StyledBalance configuration defaults added

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/receive/util/AndroidQrCodeImageGenerator.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/scan/util/ImageUriToQrCodeConverter.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/scan/util/QrCodeAnalyzer.kt
[^4]: _Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be …
> QR scanner better cropping & support for inverted colors

- build-conventions-secant/src/main/kotlin/publish/ChangelogEntry.kt
- Closes #1524
- Note that this intentionally removes the extra new line after every section to save some space.
> **Note**
> **Note**
[^2]: _While we aim for automated …
> [#1524] Restrict Google Play In-app update notes length

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- ui-lib/src/main/AndroidManifest.xml
Actions like send transaction are executed on lifecycle of activity which is killed during config change. However we are leveraging full compose and can let the activity handle it. …
> Activity configuration handling

- CHANGELOG.md
- app/src/androidTest/java/co/electriccoin/zcash/app/AndroidApiTest.kt
- gradle.properties
- Closes #1512
- Chnagelog update
> **Note**
> **Note** …
> [#1512] Bump targetSdk to version 34

- CHANGELOG.md
- gradle.properties
Closes #1531
> **Note**
> **Note** …
> [#1531] Switch to non-snapshot Zcash SDK version

- docs/whatsNew/WHATS_NEW_EN.md
> Updated WHATS_NEW_EN for 1.1.4 release.md

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- gradle.properties
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/WalletViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/model/WalletDisplayValues.kt
- ui-lib/src/main/res/ui/balances/values/strings.xml
- Closes #1547
> **Note**
> **Note** …
> [#1547] Adopt latest Zcash SDK v2.1.3

- CHANGELOG.md
- build-conventions-secant/src/main/kotlin/publish/ChangelogParser.kt
- docs/whatsNew/WHATS_NEW_EN.md
- gradle.properties
- App version and changelogs update
- Improved wahtsnew file parsing
- Closes #1549
> **Note**
> **Note**
[^2]: _While we aim for automated testing of the application, some …
> [ #1549] Release Zashi version 1.1.5 (706)

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- gradle.properties
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/compose/BalanceWidget.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/extension/LocaleExt.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/model/WalletDisplayValues.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/exchangerate/widget/StyledExchangeBalance.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/AndroidSend.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/model/AmountState.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
- These changes adopt the latest Zcash SDK v2.2.3 snapshot changes that bring simplification in Zec and Fiat APIs localization
- It fixes the bug of requesting the zec/fiat rate for non-English device locale
- Closes #1569
- Closes #1171 too
> **Note**
> **Note**
[^1]: _Code often looks …
> [#1569] Release 1.1.7 (717)

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- gradle.properties
- Closes #1571
> **Note**
> **Note** …
> [#1571] Release 1.1.7 (718)

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/AndroidBalances.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/model/ShieldState.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/balances/view/BalancesView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/sendconfirmation/AndroidSendConfirmation.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/sendconfirmation/model/SendConfirmationStage.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/sendconfirmation/model/SubmitResult.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/sendconfirmation/view/SendConfirmationView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/sendconfirmation/viewmodel/CreateTransactionsViewModel.kt
- ui-lib/src/main/res/ui/balances/values/strings.xml
- ui-lib/src/main/res/ui/send_confirmation/values/strings.xml
- Closes #1419
- The latest Zcash SDK Trx resubmission changes adopted within Zashi
- These changes resolve both use cases: Sent funds and Shield transparent funds 
- These changes improve the texts for not grpc transaction errors, too
> **Note**
> **Note**
[^1]: _Code …
> [#1419] TRX Resubmission

- gradle.properties
Closes #1578
> **Note**
> **Note** …
> [#1578] Switch to production Zcash SDK v2.2.3

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/WalletViewModel.kt
> Fix stacktrace printing

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- gradle.properties
- Closes #1584
> **Note**
> **Note** …
> [#1584] Release 1.2 (729)

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- Closes #1586
> **Note**
> **Note** …
> [#1586] Release 1.2 (730)

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- gradle.properties
- Adopted the fixed production Zcash SDK v2.2.4
> **Note**
> **Note** …
> [#1589] Release 1.2 (731)

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/util/EmailUtil.kt
- Closes #1597
> **Note**
> **Note** …
> [#1597] Improve EmailUtils Intent for more clients

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- Closes #1599
> **Note**
> **Note** …
> [#1599] Release 1.2 (735)

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- gradle.properties
- sdk-ext-lib/src/main/java/cash/z/ecc/sdk/fixture/PersistableWalletFixture.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/viewmodel/RestoreViewModel.kt
- Adopted the Zcash SDK 2.2.5-SNAPSHOT version
- Closes https://github.com/Electric-Coin-Company/zashi-android/issues/1608
> **Note**
> **Note**
[^2]: …
> [#1608] Release 1.2 (739)

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/ZashiTextField.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/sendconfirmation/view/SendConfirmationView.kt
- ui-lib/src/main/res/ui/send/values/strings.xml
- ui-lib/src/main/res/ui/send_confirmation/drawable/ic_confirmation_message_info.xml
- ui-lib/src/main/res/ui/send_confirmation/values/strings.xml
> Confirmation screen redesign

- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/contact/viewmodel/AddContactViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/contact/viewmodel/UpdateContactViewModel.kt
> Fixed address book field state handling

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- ui-lib/build.gradle.kts
- ui-lib/src/main/java/co/electriccoin/zcash/di/DateSourceModule.kt
- ui-lib/src/main/java/co/electriccoin/zcash/di/UseCaseModule.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/MainActivity.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/datasource/LocalAddressBookDataSource.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/datasource/RemoteAddressBookDataSource.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/repository/AddressBookRepository.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/usecase/DeleteAddressBookUseCase.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/WalletViewModel.kt
> Remote address book storage disabled & address book removal

- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/extension/ZecSendExt.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/paymentrequest/view/PaymentRequestView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/sendconfirmation/view/SendConfirmationView.kt
On the Send Confirmation and Payment Request screens
> **Note**
> **Note**
[^2]: _While we aim for automated testing of the application, some aspects require manual testing. …
> Fix total send amounts

- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/contact/viewmodel/UpdateContactViewModel.kt
> Update address book screen state fix

- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/repository/FlexaRepository.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/WalletViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/integrations/AndroidIntegrations.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/integrations/viewmodel/IntegrationsViewModel.kt
- ui-lib/src/main/res/ui/integrations/values/strings.xml
> Flexa optimization

- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/compose/BalanceWidget.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/model/WalletSnapshot.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/repository/BalanceRepository.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/repository/FlexaRepository.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/fixture/BalanceStateFixture.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/account/view/AccountView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/integrations/viewmodel/IntegrationsViewModel.kt
> Flexa hotfixes for balance and transaction failure

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- ui-lib/src/main/java/co/electriccoin/zcash/di/ViewModelModule.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/addressbook/viewmodel/AddressBookViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/AndroidSend.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/SendViewModel.kt
> Address book fix on send screen

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/Navigation.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/usecase/GetSynchronizerUseCase.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/WalletViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/deletewallet/AndroidDeleteWallet.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/AndroidRestore.kt
> Delete wallet hotfix

- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/AuthenticationViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/authentication/view/AuthenticationView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/paymentrequest/viewmodel/PaymentRequestViewModel.kt
- Omit app launch authentication when run without secrets set
> **Note**
> **Note**
[^2]: _While we aim for automated testing of the application, some aspects require manual …
> Fix app launch authentication

- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/seed/viewmodel/SeedViewModel.kt
> Seed recovery pre android 12 design

- ui-lib/src/main/java/co/electriccoin/zcash/ui/preference/StandardPreferenceKeys.kt
We can stop the decision logic even from this place, as we omit the authentication when secrets are not set yet.
> **Note**
> **Note**
[^2]: _While we aim for automated …
> Simplify first launch authentication decision

- CHANGELOG.md
- build-conventions-secant/src/main/kotlin/publish/secant.publish-conventions.gradle.kts
- docs/whatsNew/WHATS_NEW_EN.md
- docs/whatsNew/WHATS_NEW_ES.md
> Fix Release 1.2.2 notes path

- docs/Auto Backup.md
- docs/README.md
- docs/integrations/Flexa.md
> Flexa adoption documentation

- build-conventions-secant/src/main/kotlin/publish/ChangelogParser.kt
- docs/whatsNew/WHATS_NEW_ES.md
> Update Spanish Changelog titles

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- docs/whatsNew/WHATS_NEW_ES.md
> Release 1.2.3 (799)

- CHANGELOG.md
- app/proguard-project.txt
- docs/whatsNew/WHATS_NEW_EN.md
- docs/whatsNew/WHATS_NEW_ES.md
- gradle.properties
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/ZashiMainTopAppBar.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/viewmodel/ZashiMainTopAppBarViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/fixture/ZashiMainTopAppBarStateFixture.kt
- ui-lib/src/main/res/ui/common/values-es/strings.xml
- ui-lib/src/main/res/ui/common/values/strings.xml
Closes #1672
> **Note**
> **Note** …
> [#1672] Release Zashi version 1.3

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- docs/whatsNew/WHATS_NEW_ES.md
- gradle.properties
> Release 1.3.1

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- docs/whatsNew/WHATS_NEW_ES.md
- gradle.properties
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/usecase/Zip321ParseUriValidationUseCase.kt
- Changelogs
- Version name
- Closes #1725
> **Note**
> **Note**
[^2]: _While we aim for automated testing of the application, some aspects require manual testing. If you had …
> [#1725] Release 1.3.2 (828)

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- docs/whatsNew/WHATS_NEW_ES.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/ZashiQr.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/qrcode/view/QrCodeView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/request/view/RequestQrCodeView.kt
- QR code for KS confirmation background color fixed
- Changelogs updated
- Closes #1725
> **Note**
> **Note**
[^2]: _While we aim for automated testing of the application, …
> [#1725] Release 1.3.2 (829)

- CHANGELOG.md
- app/build.gradle.kts
- app/src/main/java/co/electriccoin/zcash/app/ZcashApplication.kt
- docs/whatsNew/WHATS_NEW_EN.md
- docs/whatsNew/WHATS_NEW_ES.md
- settings.gradle.kts
- ui-lib/src/main/java/co/electriccoin/zcash/di/ProviderModule.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/Navigation.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/provider/ApplicationStateProvider.kt
> App state check for disconnected resolution

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- docs/whatsNew/WHATS_NEW_ES.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/compose/SynchronizationStatus.kt
- This is especially important now when importing the Keystone device without providing the add-birthday feature to users
- Closes #1735
- Changelogs updated
> **Note**
> **Note** …
> [#1735] Set uncompleted block sync percentage

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- docs/whatsNew/WHATS_NEW_ES.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/Navigation.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/NavigationRouter.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/usecase/ParseKeystoneSignInRequestUseCase.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/usecase/ViewTransactionsAfterSuccessfulProposalUseCase.kt
> Navigation hotfix for new root navigation

- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/request/model/Request.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/request/model/RequestState.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/request/view/RequestView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/request/viewmodel/RequestViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/SendViewModel.kt
- Closes #1737 
- This PR also addresses broken QR code image from ZIP321 for the `Request` screen flow.
> **Note**
> **Note**
[^2]: _While we aim for automated testing of the …
> [#1737] Create transaction error handling

- app/build.gradle.kts
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/balances/BalancesTestSetup.kt
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/balances/model/WalletDisplayValuesTest.kt
- Fix app name
- Tests fix
> **Note**
> **Note**
[^2]: _While we aim for automated testing of the application, some aspects require manual testing. If you had to manually test …
> Minor alternative-stores changes

- .github/workflows/deploy.yml
- .github/workflows/pull-request.yml
- .github/workflows/release.yaml
- README.md
- app/build.gradle.kts
- build.gradle.kts
- docs/CI.md
- gradle.properties
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/settings/viewmodel/SettingsViewModel.kt
- ui-lib/src/main/res/ui/non_translatable/values/strings.xml
> F-Droid reproducible builds

- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/mapper/TransactionHistoryMapper.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/repository/TransactionRepository.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/usecase/ExportTaxUseCase.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/usecase/GetCurrentFilteredTransactionsUseCase.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/usecase/GetCurrentTransactionsUseCase.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/usecase/GetTransactionDetailByIdUseCase.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/AndroidSend.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/transactiondetail/TransactionDetailViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/transactionhistory/TransactionHistoryViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/transactionhistory/widget/TransactionHistoryWidgetViewModel.kt
> Transaction code cleanup

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- docs/whatsNew/WHATS_NEW_ES.md
- fastlane/metadata/android/en-US/changelogs/873.txt
- fastlane/metadata/android/es/changelogs/873.txt
- gradle.properties
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/taxexport/AndroidTaxExport.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/taxexport/TaxExportState.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/taxexport/TaxExportView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/taxexport/TaxExportViewModel.kt
- ui-lib/src/main/res/ui/tax_export/values-es/strings.xml
- ui-lib/src/main/res/ui/tax_export/values/strings.xml
> [#1801] Release Android Zashi v1.4

- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/view/OnboardingView.kt
- ui-lib/src/main/res/ui/onboarding/values-es/strings.xml
- ui-lib/src/main/res/ui/onboarding/values/strings.xml
- ui-screenshot-test/src/main/java/co/electroniccoin/zcash/ui/screenshot/ScreenshotTest.kt
| eng  | es |
| ------------- | ------------- |
| ![Snímka obrazovky 2025-03-04 o 11 38 21](https://github.com/user-attachments/assets/ec6d8f85-a250-4a52-87a0-6fd938706fc7)  | ![Snímka obrazovky 2025-03-04 o 11 38 47](https://github.com/user-attachments/assets/4508adef-6512-4e75-bf91-e4f5f10b3016)  |
> **Note**
[^3]: …
> Copy update on onboarding

- .github/ISSUE_TEMPLATE/app-release.md
- Closes #1517 
- This new GitHub template covers our two-step release process to Google Play and GitHub Releases, which triggers the F-Droid deployment process as well.
> **Note**
> **Note**
[^1]: _Code often looks different when reviewing the diff in a browser, making it easier to spot …
> Release issue GitHub template

- gradle.properties
> Adopt Zcash SDK v2.2.9-SNAPSHOT

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- docs/whatsNew/WHATS_NEW_ES.md
- fastlane/metadata/android/en-US/changelogs/925.txt
- fastlane/metadata/android/es/changelogs/925.txt
- gradle.properties
Closes #1840 
> **Note**
> **Note** …
> [#1840] Android Zashi Release v1.5.1 (925)

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- docs/whatsNew/WHATS_NEW_ES.md
- fastlane/metadata/android/en-US/changelogs/926.txt
- fastlane/metadata/android/es/changelogs/926.txt
- gradle.properties
Closes #1843
> **Note**
> **Note** …
> [#1843] Release v1.5.2

- CHANGELOG.md
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/AndroidOnboarding.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/viewmodel/OnboardingViewModel.kt
- Closes #1846
> **Note**
> **Note** …
> [#1846] Remove Security Warning from FOSS

- gradle.properties
> Adopt production Zcash SDK v2.2.11

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- docs/whatsNew/WHATS_NEW_ES.md
- fastlane/metadata/android/en-US/changelogs/929.txt
- fastlane/metadata/android/es/changelogs/929.txt
Closes #1849 
> **Note**
> **Note** …
> [#1849] Release 1.5.2 (929)

- CHANGELOG.md
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/ZashiBigIconButton.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/usecase/OnZip321ScannedUseCase.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/usecase/PrefillSendUseCase.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/usecase/SendTransactionAgainUseCase.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/HomeView.kt
> 2.0.1 bugfixes

- ui-lib/src/main/res/ui/send_confirmation/values-es/strings.xml
- ui-lib/src/main/res/ui/send_confirmation/values/strings.xml
- ui-screenshot-test/src/main/java/co/electroniccoin/zcash/ui/screenshot/ScreenshotTest.kt
> Texts update

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- docs/whatsNew/WHATS_NEW_ES.md
- fastlane/metadata/android/en-US/changelogs/941.txt
- fastlane/metadata/android/es/changelogs/941.txt
- gradle.properties
Closes #1862
> **Note**
> **Note** …
> Release: 2.0.1 (941)

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- docs/whatsNew/WHATS_NEW_ES.md
- fastlane/metadata/android/en-US/changelogs/962.txt
- fastlane/metadata/android/es/changelogs/962.txt
- gradle.properties
Closes #1872
| es | en |
|---------------|---------------|
| ![Screenshot_20250514_134003](https://github.com/user-attachments/assets/4794cfea-31b8-4ea5-9635-8ca43975ba4c) | ![Screenshot_20250514_134018](https://github.com/user-attachments/assets/eb71259e-16d2-4bf8-bed4-08fb3bdfc4c7) |
> **Note**
> **Note**
> It is good practice to provide before and after UI  **screenshots** in the description of this PR. This is only applicable for changes …
> Release: 2.0.2 (962)

- CHANGELOG.md
- preference-impl-android-lib/src/main/java/co/electriccoin/zcash/preference/AndroidPreferenceProvider.kt
> Shared preferences object cached in-memory and locked with semaphore

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- docs/whatsNew/WHATS_NEW_ES.md
- fastlane/metadata/android/en-US/changelogs/965.txt
- fastlane/metadata/android/es/changelogs/965.txt
- gradle.properties
| en | es |
|----------|----------|
| ![Screenshot_20250519_124641](https://github.com/user-attachments/assets/af755270-790d-4d15-9713-1641f3a2414f) | ![Screenshot_20250519_124703](https://github.com/user-attachments/assets/d828b3aa-a5eb-4fdf-9092-93ed8862f036) |
Closes #1876
> **Note**
> **Note**
> It is good practice to provide before and after UI  **screenshots** in the description of this PR. This is only applicable for changes that …
> [#1876] Release: 2.0.3 (965)

- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/ZashiNumberTextField.kt
- ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/util/StringResource.kt
- ui-lib/src/main/java/co/electriccoin/zcash/di/UseCaseModule.kt
- ui-lib/src/main/java/co/electriccoin/zcash/di/ViewModelModule.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/Navigation.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/repository/SwapRepository.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/usecase/GetSlippageUseCase.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/usecase/SetSlippageUseCase.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/swap/amount/SwapAmountView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/swap/amount/SwapAmountViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/swap/amount/SwapText.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/swap/amount/SwapTextField.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/swap/pay/PaySwapView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/swap/pay/SwapTokenAmount.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/swap/slippage/SlippageSlider.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/swap/slippage/SwapSlippageScreen.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/swap/slippage/SwapSlippageState.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/swap/slippage/SwapSlippageView.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/swap/slippage/SwapSlippageViewModel.kt
> Swap slippage screen business logic

- ui-lib/src/main/java/co/electriccoin/zcash/di/CoreModule.kt
- ui-lib/src/main/java/co/electriccoin/zcash/global/WalletCoordinator.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/datasource/ZashiSpendingKeyDataSource.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/provider/PersistableWalletProvider.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/repository/AddressBookRepository.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/repository/MetadataRepository.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/repository/WalletRepository.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/usecase/DeriveKeystoneAccountUnifiedAddressUseCase.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/usecase/ObservePersistableWalletUseCase.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/usecase/PersistEndpointUseCase.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/usecase/RescanQrUseCase.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/estimation/RestoreBDEstimationViewModel.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/restore/height/RestoreBDHeightView.kt
> Persistable wallet retrieval crash hotfix

- CHANGELOG.md
- ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/send/SendViewTestSetup.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/repository/WalletRepository.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/AndroidSend.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/model/AmountState.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/send/view/SendView.kt
> Number user input

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- docs/whatsNew/WHATS_NEW_ES.md
- fastlane/metadata/android/en-US/changelogs/996.txt
- fastlane/metadata/android/es/changelogs/996.txt
- gradle.properties
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/receive/ReceiveVM.kt
- ui-lib/src/main/res/ui/receive/values-es/strings.xml
- ui-lib/src/main/res/ui/receive/values/strings.xml
Closes #1903
> **Note**
> **Note** …
> [#1903] Release: 2.1.0 (996)

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- docs/whatsNew/WHATS_NEW_ES.md
- fastlane/metadata/android/en-US/changelogs/997.txt
- fastlane/metadata/android/es/changelogs/997.txt
- ui-lib/src/main/res/ui/advanced_settings/values-es/strings.xml
- ui-lib/src/main/res/ui/advanced_settings/values/strings.xml
- ui-lib/src/main/res/ui/tor/values-es/strings.xml
- ui-lib/src/main/res/ui/tor/values/strings.xml
> [#1905] Release: 2.1.0 (997)

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- docs/whatsNew/WHATS_NEW_ES.md
- fastlane/metadata/android/en-US/changelogs/1120.txt
- fastlane/metadata/android/es/changelogs/1120.txt
- gradle.properties
Closes #1915
> **Note**
> **Note** …
> [#1915] Release: 2.2.0 (1020)

- CHANGELOG.md
- build-conventions-secant/src/main/kotlin/secant.emulator-wtf-conventions.gradle.kts
- docs/whatsNew/WHATS_NEW_EN.md
- docs/whatsNew/WHATS_NEW_ES.md
- fastlane/metadata/android/en-US/changelogs/1121.txt
- fastlane/metadata/android/es/changelogs/1121.txt
- gradle.properties
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/datasource/MetadataDataSource.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/provider/MetadataKeyStorageProvider.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/repository/KeystoneProposalRepository.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/repository/MetadataRepository.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/repository/WalletRepository.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/repository/ZashiProposalRepository.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/serialization/metada/MetadataKey.kt
> [#1918] Release 2.2.1 (1121)

- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/transactionprogress/TransactionProgressState.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/transactionprogress/TransactionProgressVM.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/transactionprogress/TransactionProgressView.kt
> Allow to open trx from GRPC error screen

- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/datasource/LocalAddressBookDataSource.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/model/AddressBook.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/serialization/BaseSerializer.kt
- ui-lib/src/main/java/co/electriccoin/zcash/ui/common/serialization/addressbook/AddressBookSerializer.kt
> Hotfix for AB deserialization error of empty string

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- docs/whatsNew/WHATS_NEW_ES.md
- fastlane/metadata/android/en-US/changelogs/1225.txt
- fastlane/metadata/android/es/changelogs/1225.txt
Closes #1933
> **Note**
> **Note** …
> [#1933] Release: 2.4.0 (1225)

- CHANGELOG.md
- docs/whatsNew/WHATS_NEW_EN.md
- docs/whatsNew/WHATS_NEW_ES.md
- fastlane/metadata/android/en-US/changelogs/1239.txt
- fastlane/metadata/android/es/changelogs/1239.txt
- gradle.properties
- ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/transactionhistory/widget/TransactionHistoryWidget.kt
Closes #1938
> **Note**
> **Note** …
> [#1938] Release: 2.4.1 (1239)
